--  Drop old dependent tables first
DROP TABLE IF EXISTS district_adjacency_bonuses;
DROP TABLE IF EXISTS district_tile_bonuses;
DROP TABLE IF EXISTS district_info;

-- unlock legacy depends on treaty/convertor
DROP TABLE IF EXISTS tech_unlocks;
DROP TABLE IF EXISTS tech_unlock;

-- now safe to drop reference tables
DROP TABLE IF EXISTS treaty;
DROP TABLE IF EXISTS convertor;

-- If present (new schema table name)
DROP TABLE IF EXISTS district_description_lines;

--  Drop old districts table
DROP TABLE IF EXISTS districts;

--  New districts table
CREATE TABLE districts (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           district_key VARCHAR(220) NOT NULL,
                           display_name VARCHAR(400) NOT NULL,
                           category VARCHAR(200),

                           CONSTRAINT uq_district_key UNIQUE (district_key)
);

--  Ordered element collection table
CREATE TABLE district_description_lines (
                                            district_id BIGINT NOT NULL,
                                            line_index INT NOT NULL,
                                            line VARCHAR(800) NOT NULL,

                                            CONSTRAINT pk_district_description_lines PRIMARY KEY (district_id, line_index),
                                            CONSTRAINT fk_district_description_lines_district
                                                FOREIGN KEY (district_id)
                                                    REFERENCES districts (id)
                                                    ON DELETE CASCADE
);

CREATE INDEX idx_district_description_lines_district_id
    ON district_description_lines (district_id);