-- Drop legacy child tables first (FK dependencies)
DROP TABLE IF EXISTS improvement_costs;
DROP TABLE IF EXISTS improvement_effects;

-- Drop legacy parent table
DROP TABLE IF EXISTS improvements;

-- Create new improvements table
CREATE TABLE improvements (
                              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              constructible_key VARCHAR(255) NOT NULL,
                              display_name VARCHAR(400) NOT NULL,
                              category VARCHAR(200),
                              CONSTRAINT uq_improvement_constructible_key UNIQUE (constructible_key)
);

CREATE INDEX ix_improvements_constructible_key
    ON improvements (constructible_key);

-- Create ordered description lines table
CREATE TABLE improvement_description_lines (
                                               improvement_id BIGINT NOT NULL,
                                               line_index INT NOT NULL,
                                               line TEXT NOT NULL,

                                               CONSTRAINT pk_improvement_description_lines
                                                   PRIMARY KEY (improvement_id, line_index),

                                               CONSTRAINT fk_improvement_desc_lines_improvement
                                                   FOREIGN KEY (improvement_id)
                                                       REFERENCES improvements (id)
                                                       ON DELETE CASCADE
);