-- V3_2_3__tech_import_v0_add_baseline_and_children.sql
-- Additive-only schema for Tech import v0.
-- Target: Postgres (prod) + fresh H2 in-memory (local).

------------------------------------------------------------
-- 1) tech: baseline/import-owned columns
-- Note: quadrant is already stored as tech.type (TechType values match),
-- so we do NOT add a new quadrant column.
------------------------------------------------------------
alter table tech add column tech_key varchar(255);
alter table tech add column baseline_hash varchar(64);
alter table tech add column lore text;
alter table tech add column hidden boolean;

-- Helpful index for importer upsert lookup (unique constraint added later)
create index ix_tech_tech_key on tech (tech_key);

------------------------------------------------------------
-- 2) tech_unlock: raw unlock tuple fields (store now, resolve later)
-- Keep existing FK columns untouched.
------------------------------------------------------------
alter table tech_unlock add column unlock_type varchar(64);
alter table tech_unlock add column unlock_category varchar(64);
alter table tech_unlock add column unlock_element_name varchar(255);

------------------------------------------------------------
-- 3) Imported child tables (string-key based)
-- These preserve exporter meaning and support multi-prereq future.
------------------------------------------------------------

-- 3a) technologyPrerequisiteTechKeys[]
create table tech_prereq_key (
                                 id bigint generated by default as identity primary key,
                                 tech_id bigint not null,
                                 prereq_tech_key varchar(255) not null,
                                 constraint fk_tech_prereq_key_tech foreign key (tech_id) references tech (id)
);

create unique index ux_tech_prereq_key
    on tech_prereq_key (tech_id, prereq_tech_key);

-- 3b) exclusiveTechnologyPrerequisiteTechKeys[]
create table tech_exclusive_prereq_key (
                                           id bigint generated by default as identity primary key,
                                           tech_id bigint not null,
                                           exclusive_prereq_tech_key varchar(255) not null,
                                           constraint fk_tech_exclusive_prereq_key_tech foreign key (tech_id) references tech (id)
);

create unique index ux_tech_exclusive_prereq_key
    on tech_exclusive_prereq_key (tech_id, exclusive_prereq_tech_key);

-- 3c) factionTraitPrerequisites[] (operator + traitKey)
-- Keep legacy tech_entity_factions as-is; this table stores raw prereq rules.
create table tech_trait_prereq (
                                   id bigint generated by default as identity primary key,
                                   tech_id bigint not null,
                                   operator varchar(32) not null,
                                   trait_key varchar(255) not null,
                                   constraint fk_tech_trait_prereq_tech foreign key (tech_id) references tech (id)
);

create unique index ux_tech_trait_prereq
    on tech_trait_prereq (tech_id, operator, trait_key);