CREATE TABLE IF NOT EXISTS units (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     unit_key VARCHAR(255) NOT NULL,
                                     display_name VARCHAR(255) NOT NULL,
                                     is_hero BOOLEAN NOT NULL,
                                     is_chosen BOOLEAN NOT NULL,
                                     spawn_type VARCHAR(64),
                                     previous_unit_key VARCHAR(255),
                                     evolution_tier_index INTEGER,
                                     unit_class_key VARCHAR(255),
                                     attack_skill_key VARCHAR(255),
                                     CONSTRAINT uq_units_unit_key UNIQUE (unit_key)
);

CREATE TABLE IF NOT EXISTS unit_next_evolutions (
                                                    unit_id BIGINT NOT NULL,
                                                    next_index INTEGER NOT NULL,
                                                    next_unit_key VARCHAR(255) NOT NULL,
                                                    CONSTRAINT pk_unit_next_evolutions PRIMARY KEY (unit_id, next_index),
                                                    CONSTRAINT fk_unit_next_evolutions_unit
                                                        FOREIGN KEY (unit_id) REFERENCES units(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS unit_abilities (
                                              unit_id BIGINT NOT NULL,
                                              ability_index INTEGER NOT NULL,
                                              ability_key VARCHAR(255) NOT NULL,
                                              CONSTRAINT pk_unit_abilities PRIMARY KEY (unit_id, ability_index),
                                              CONSTRAINT fk_unit_abilities_unit
                                                  FOREIGN KEY (unit_id) REFERENCES units(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS unit_description_lines (
                                                      unit_id BIGINT NOT NULL,
                                                      line_index INTEGER NOT NULL,
                                                      line TEXT NOT NULL,
                                                      CONSTRAINT pk_unit_description_lines PRIMARY KEY (unit_id, line_index),
                                                      CONSTRAINT fk_unit_description_lines_unit
                                                          FOREIGN KEY (unit_id) REFERENCES units(id) ON DELETE CASCADE
);

-- Helpful lookup indexes (optional but recommended)
CREATE INDEX IF NOT EXISTS ix_units_unit_key ON units(unit_key);
CREATE INDEX IF NOT EXISTS ix_unit_next_evolutions_unit_id ON unit_next_evolutions(unit_id);
CREATE INDEX IF NOT EXISTS ix_unit_abilities_unit_id ON unit_abilities(unit_id);
CREATE INDEX IF NOT EXISTS ix_unit_description_lines_unit_id ON unit_description_lines(unit_id);