CREATE TABLE quests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quest_key VARCHAR(220) NOT NULL,
    display_name VARCHAR(400),
    description_lines TEXT,
    category_key VARCHAR(220),
    category_type VARCHAR(120),
    is_branch_start BOOLEAN NOT NULL,
    is_branch_end BOOLEAN NOT NULL,
    is_mandatory BOOLEAN NOT NULL,
    is_key_narrative_beat BOOLEAN NOT NULL,
    is_narrative_victory_path_choice BOOLEAN NOT NULL,
    chapter_key VARCHAR(220),
    chapter_index INTEGER,
    chapter_number INTEGER,
    quest_sequence_index INTEGER,
    branch_group_key VARCHAR(220),
    branch_label VARCHAR(220),
    inferred_faction_key VARCHAR(220),
    inferred_quest_line_key VARCHAR(220),
    converges_into_quest_key VARCHAR(220),
    previous_quest_keys TEXT,
    next_quest_keys TEXT,
    reference_keys TEXT,
    CONSTRAINT uq_quests_quest_key UNIQUE (quest_key)
);

CREATE TABLE quest_choices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quest_id BIGINT NOT NULL,
    choice_key VARCHAR(220) NOT NULL,
    choice_order INTEGER NOT NULL,
    display_name VARCHAR(400),
    description_lines TEXT,
    completion_prerequisite_lines TEXT,
    failure_prerequisite_lines TEXT,
    reward_display_lines TEXT,
    next_quest_keys TEXT,
    reference_keys TEXT,
    CONSTRAINT fk_quest_choices_quest
        FOREIGN KEY (quest_id) REFERENCES quests(id) ON DELETE CASCADE,
    CONSTRAINT uq_quest_choices_quest_choice_key UNIQUE (quest_id, choice_key)
);

CREATE TABLE quest_steps (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    choice_id BIGINT NOT NULL,
    step_index INTEGER NOT NULL,
    step_order INTEGER NOT NULL,
    objective_text TEXT,
    next_quest_key VARCHAR(220),
    fail_quest_key VARCHAR(220),
    description_lines TEXT,
    completion_prerequisite_lines TEXT,
    failure_prerequisite_lines TEXT,
    forbidden_prerequisite_lines TEXT,
    selection_prerequisite_lines TEXT,
    reward_display_lines TEXT,
    reference_keys TEXT,
    CONSTRAINT fk_quest_steps_choice
        FOREIGN KEY (choice_id) REFERENCES quest_choices(id) ON DELETE CASCADE,
    CONSTRAINT uq_quest_steps_choice_step_index UNIQUE (choice_id, step_index)
);

CREATE TABLE quest_dialog_blocks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quest_id BIGINT NOT NULL,
    choice_id BIGINT,
    step_id BIGINT,
    dialog_identity VARCHAR(700) NOT NULL,
    parent_scope VARCHAR(24) NOT NULL,
    block_order INTEGER NOT NULL,
    source_quest_key VARCHAR(220) NOT NULL,
    source_choice_key VARCHAR(220),
    source_step_index INTEGER,
    dialog_key VARCHAR(220) NOT NULL,
    phase VARCHAR(80) NOT NULL,
    expected_line_count INTEGER NOT NULL,
    CONSTRAINT fk_quest_dialog_blocks_quest
        FOREIGN KEY (quest_id) REFERENCES quests(id) ON DELETE CASCADE,
    CONSTRAINT fk_quest_dialog_blocks_choice
        FOREIGN KEY (choice_id) REFERENCES quest_choices(id) ON DELETE CASCADE,
    CONSTRAINT fk_quest_dialog_blocks_step
        FOREIGN KEY (step_id) REFERENCES quest_steps(id) ON DELETE CASCADE,
    CONSTRAINT uq_quest_dialog_blocks_identity UNIQUE (dialog_identity)
);

CREATE TABLE quest_dialog_lines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dialog_block_id BIGINT NOT NULL,
    line_order INTEGER NOT NULL,
    source_line_index INTEGER,
    role VARCHAR(80),
    speaker_label VARCHAR(220),
    text TEXT NOT NULL,
    CONSTRAINT fk_quest_dialog_lines_block
        FOREIGN KEY (dialog_block_id) REFERENCES quest_dialog_blocks(id) ON DELETE CASCADE,
    CONSTRAINT uq_quest_dialog_lines_block_line_order UNIQUE (dialog_block_id, line_order)
);

CREATE INDEX idx_quest_choices_quest_id ON quest_choices(quest_id);
CREATE INDEX idx_quest_steps_choice_id ON quest_steps(choice_id);
CREATE INDEX idx_quest_dialog_blocks_quest_id ON quest_dialog_blocks(quest_id);
CREATE INDEX idx_quest_dialog_blocks_dialog_key ON quest_dialog_blocks(dialog_key);
CREATE INDEX idx_quest_dialog_lines_block_id ON quest_dialog_lines(dialog_block_id);
