create table codex
(
    id           bigint generated by default as identity primary key,
    export_kind  varchar(80)  not null,
    entry_key    varchar(220) not null,
    display_name varchar(400) not null,
    constraint uq_codex_kind_key unique (export_kind, entry_key)
);

create table codex_description_lines
(
    codex_id   bigint       not null references codex on delete cascade,
    line_index integer      not null,
    line       varchar(800) not null,
    constraint pk_codex_description_lines primary key (codex_id, line_index)
);

create index idx_codex_description_lines_codex_id
    on codex_description_lines (codex_id);

create table codex_reference_keys
(
    codex_id   bigint       not null references codex on delete cascade,
    ref_index  integer      not null,
    ref_key    varchar(220) not null,
    constraint pk_codex_reference_keys primary key (codex_id, ref_index)
);

create index idx_codex_reference_keys_codex_id
    on codex_reference_keys (codex_id);

create index idx_codex_reference_keys_ref_key
    on codex_reference_keys (ref_key);

create unique index uq_codex_reference_keys_key
    on codex_reference_keys (codex_id, ref_key);