DROP TABLE IF EXISTS quest_chronicle_transcript_lines;
DROP TABLE IF EXISTS quest_chronicle_transcript_blocks;
DROP TABLE IF EXISTS quest_chronicle_rewards;
DROP TABLE IF EXISTS quest_chronicle_requirements;
DROP TABLE IF EXISTS quest_chronicle_paths;
DROP TABLE IF EXISTS quest_chronicle_objectives;
DROP TABLE IF EXISTS quest_chronicle_source_aliases;
DROP TABLE IF EXISTS quest_chronicle_entries;
DROP TABLE IF EXISTS quest_chronicle_import_batches;

CREATE TABLE quest_explorer_import_metadata (
    id BIGINT PRIMARY KEY,
    game_version VARCHAR(80),
    exporter_version VARCHAR(80),
    exported_at_utc VARCHAR(80),
    export_kind VARCHAR(80) NOT NULL,
    schema_version VARCHAR(80) NOT NULL,
    imported_at TIMESTAMP NOT NULL
);

CREATE TABLE quest_explorer_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entry_key VARCHAR(300) NOT NULL,
    title VARCHAR(500) NOT NULL,
    quest_type VARCHAR(160),
    is_mandatory BOOLEAN,
    is_key_narrative_beat BOOLEAN,
    CONSTRAINT uq_quest_explorer_entries_entry_key UNIQUE (entry_key)
);

CREATE TABLE quest_explorer_entry_summary_lines (
    entry_id BIGINT NOT NULL,
    line_order INTEGER NOT NULL,
    line TEXT NOT NULL,
    CONSTRAINT fk_quest_explorer_summary_entry
        FOREIGN KEY (entry_id) REFERENCES quest_explorer_entries(id) ON DELETE CASCADE
);

CREATE TABLE quest_explorer_aliases (
    entry_id BIGINT NOT NULL,
    alias_order INTEGER NOT NULL,
    alias VARCHAR(300) NOT NULL,
    CONSTRAINT fk_quest_explorer_alias_entry
        FOREIGN KEY (entry_id) REFERENCES quest_explorer_entries(id) ON DELETE CASCADE
);

CREATE TABLE quest_explorer_quality_warnings (
    entry_id BIGINT NOT NULL,
    warning_order INTEGER NOT NULL,
    warning TEXT NOT NULL,
    CONSTRAINT fk_quest_explorer_quality_entry
        FOREIGN KEY (entry_id) REFERENCES quest_explorer_entries(id) ON DELETE CASCADE
);

CREATE TABLE quest_explorer_navigation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entry_id BIGINT NOT NULL,
    faction_key VARCHAR(260),
    faction_name VARCHAR(260),
    quest_line_key VARCHAR(260),
    quest_line_name VARCHAR(260),
    chapter INTEGER,
    chapter_label VARCHAR(160),
    step INTEGER,
    step_label VARCHAR(160),
    sequence_index INTEGER NOT NULL,
    chapter_order INTEGER,
    step_order INTEGER,
    branch_group_key VARCHAR(300),
    branch_label VARCHAR(260),
    branch_order INTEGER,
    is_branch_start BOOLEAN,
    is_branch_end BOOLEAN,
    CONSTRAINT fk_quest_explorer_navigation_entry
        FOREIGN KEY (entry_id) REFERENCES quest_explorer_entries(id) ON DELETE CASCADE,
    CONSTRAINT uq_quest_explorer_navigation_entry UNIQUE (entry_id)
);

CREATE TABLE quest_explorer_navigation_previous_entries (
    navigation_id BIGINT NOT NULL,
    link_order INTEGER NOT NULL,
    entry_key VARCHAR(300) NOT NULL,
    CONSTRAINT fk_quest_explorer_nav_previous
        FOREIGN KEY (navigation_id) REFERENCES quest_explorer_navigation(id) ON DELETE CASCADE
);

CREATE TABLE quest_explorer_navigation_next_entries (
    navigation_id BIGINT NOT NULL,
    link_order INTEGER NOT NULL,
    entry_key VARCHAR(300) NOT NULL,
    CONSTRAINT fk_quest_explorer_nav_next
        FOREIGN KEY (navigation_id) REFERENCES quest_explorer_navigation(id) ON DELETE CASCADE
);

CREATE TABLE quest_explorer_navigation_failure_entries (
    navigation_id BIGINT NOT NULL,
    link_order INTEGER NOT NULL,
    entry_key VARCHAR(300) NOT NULL,
    CONSTRAINT fk_quest_explorer_nav_failure
        FOREIGN KEY (navigation_id) REFERENCES quest_explorer_navigation(id) ON DELETE CASCADE
);

CREATE TABLE quest_explorer_navigation_convergence_entries (
    navigation_id BIGINT NOT NULL,
    link_order INTEGER NOT NULL,
    entry_key VARCHAR(300) NOT NULL,
    CONSTRAINT fk_quest_explorer_nav_convergence
        FOREIGN KEY (navigation_id) REFERENCES quest_explorer_navigation(id) ON DELETE CASCADE
);

CREATE TABLE quest_explorer_lore_sections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entry_id BIGINT NOT NULL,
    section_order INTEGER,
    section_key VARCHAR(360) NOT NULL,
    phase VARCHAR(80) NOT NULL,
    choice_key VARCHAR(300),
    step_index INTEGER,
    objective_key VARCHAR(360),
    CONSTRAINT fk_quest_explorer_lore_sections_entry
        FOREIGN KEY (entry_id) REFERENCES quest_explorer_entries(id) ON DELETE CASCADE
);

CREATE TABLE quest_explorer_lore_lines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    section_id BIGINT NOT NULL,
    line_order INTEGER,
    speaker_label VARCHAR(260),
    role VARCHAR(80) NOT NULL,
    text TEXT NOT NULL,
    CONSTRAINT fk_quest_explorer_lore_lines_section
        FOREIGN KEY (section_id) REFERENCES quest_explorer_lore_sections(id) ON DELETE CASCADE
);

CREATE TABLE quest_explorer_objectives (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entry_id BIGINT NOT NULL,
    objective_order INTEGER,
    objective_key VARCHAR(360),
    text TEXT NOT NULL,
    phase VARCHAR(120),
    CONSTRAINT fk_quest_explorer_objectives_entry
        FOREIGN KEY (entry_id) REFERENCES quest_explorer_entries(id) ON DELETE CASCADE
);

CREATE TABLE quest_explorer_objective_requirements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    objective_id BIGINT NOT NULL,
    requirement_order INTEGER,
    requirement_key TEXT NOT NULL,
    kind VARCHAR(160) NOT NULL,
    display_text TEXT NOT NULL,
    polarity VARCHAR(80),
    group_label VARCHAR(160),
    group_order INTEGER,
    target_role VARCHAR(160),
    target_label VARCHAR(500),
    required_count INTEGER,
    duration_turns INTEGER,
    state VARCHAR(160),
    reference_kind VARCHAR(160),
    reference_key VARCHAR(300),
    reference_display_name VARCHAR(500),
    codex_entry_key VARCHAR(300),
    CONSTRAINT fk_quest_explorer_objective_requirements_objective
        FOREIGN KEY (objective_id) REFERENCES quest_explorer_objectives(id) ON DELETE CASCADE
);

CREATE TABLE quest_explorer_objective_rewards (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    objective_id BIGINT NOT NULL,
    reward_order INTEGER,
    reward_key TEXT NOT NULL,
    kind VARCHAR(160) NOT NULL,
    display_text TEXT NOT NULL,
    amount NUMERIC(18,4),
    group_label VARCHAR(160),
    group_order INTEGER,
    formula_text TEXT,
    asset_kind VARCHAR(160),
    asset_key VARCHAR(300),
    asset_display_name VARCHAR(500),
    reference_kind VARCHAR(160),
    reference_key VARCHAR(300),
    reference_display_name VARCHAR(500),
    codex_entry_key VARCHAR(300),
    target_scope_label VARCHAR(260),
    CONSTRAINT fk_quest_explorer_objective_rewards_objective
        FOREIGN KEY (objective_id) REFERENCES quest_explorer_objectives(id) ON DELETE CASCADE
);

CREATE TABLE quest_explorer_branches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entry_id BIGINT NOT NULL,
    branch_row_order INTEGER,
    branch_key VARCHAR(360) NOT NULL,
    choice_key VARCHAR(300),
    label VARCHAR(500) NOT NULL,
    order_index INTEGER,
    group_key VARCHAR(300),
    group_label VARCHAR(260),
    CONSTRAINT fk_quest_explorer_branches_entry
        FOREIGN KEY (entry_id) REFERENCES quest_explorer_entries(id) ON DELETE CASCADE
);

CREATE TABLE quest_explorer_branch_next_entries (
    branch_id BIGINT NOT NULL,
    link_order INTEGER NOT NULL,
    entry_key VARCHAR(300) NOT NULL,
    CONSTRAINT fk_quest_explorer_branch_next
        FOREIGN KEY (branch_id) REFERENCES quest_explorer_branches(id) ON DELETE CASCADE
);

CREATE TABLE quest_explorer_branch_failure_entries (
    branch_id BIGINT NOT NULL,
    link_order INTEGER NOT NULL,
    entry_key VARCHAR(300) NOT NULL,
    CONSTRAINT fk_quest_explorer_branch_failure
        FOREIGN KEY (branch_id) REFERENCES quest_explorer_branches(id) ON DELETE CASCADE
);

CREATE TABLE quest_explorer_branch_convergence_entries (
    branch_id BIGINT NOT NULL,
    link_order INTEGER NOT NULL,
    entry_key VARCHAR(300) NOT NULL,
    CONSTRAINT fk_quest_explorer_branch_convergence
        FOREIGN KEY (branch_id) REFERENCES quest_explorer_branches(id) ON DELETE CASCADE
);

CREATE TABLE quest_explorer_branch_outcome_preview_lines (
    branch_id BIGINT NOT NULL,
    line_order INTEGER NOT NULL,
    line TEXT NOT NULL,
    CONSTRAINT fk_quest_explorer_branch_preview
        FOREIGN KEY (branch_id) REFERENCES quest_explorer_branches(id) ON DELETE CASCADE
);

CREATE TABLE quest_explorer_branch_conditions (
    branch_id BIGINT NOT NULL,
    condition_order INTEGER NOT NULL,
    condition_text TEXT NOT NULL,
    CONSTRAINT fk_quest_explorer_branch_conditions
        FOREIGN KEY (branch_id) REFERENCES quest_explorer_branches(id) ON DELETE CASCADE
);

CREATE TABLE quest_explorer_branch_requirements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id BIGINT NOT NULL,
    requirement_order INTEGER,
    requirement_key TEXT NOT NULL,
    kind VARCHAR(160) NOT NULL,
    display_text TEXT NOT NULL,
    polarity VARCHAR(80),
    group_label VARCHAR(160),
    group_order INTEGER,
    target_role VARCHAR(160),
    target_label VARCHAR(500),
    required_count INTEGER,
    duration_turns INTEGER,
    state VARCHAR(160),
    reference_kind VARCHAR(160),
    reference_key VARCHAR(300),
    reference_display_name VARCHAR(500),
    codex_entry_key VARCHAR(300),
    CONSTRAINT fk_quest_explorer_branch_requirements_branch
        FOREIGN KEY (branch_id) REFERENCES quest_explorer_branches(id) ON DELETE CASCADE
);

CREATE TABLE quest_explorer_branch_rewards (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id BIGINT NOT NULL,
    reward_order INTEGER,
    reward_key TEXT NOT NULL,
    kind VARCHAR(160) NOT NULL,
    display_text TEXT NOT NULL,
    amount NUMERIC(18,4),
    group_label VARCHAR(160),
    group_order INTEGER,
    formula_text TEXT,
    asset_kind VARCHAR(160),
    asset_key VARCHAR(300),
    asset_display_name VARCHAR(500),
    reference_kind VARCHAR(160),
    reference_key VARCHAR(300),
    reference_display_name VARCHAR(500),
    codex_entry_key VARCHAR(300),
    target_scope_label VARCHAR(260),
    CONSTRAINT fk_quest_explorer_branch_rewards_branch
        FOREIGN KEY (branch_id) REFERENCES quest_explorer_branches(id) ON DELETE CASCADE
);

CREATE INDEX idx_quest_explorer_aliases_alias ON quest_explorer_aliases(alias);
CREATE INDEX idx_quest_explorer_navigation_entry ON quest_explorer_navigation(entry_id);
CREATE INDEX idx_quest_explorer_navigation_sequence ON quest_explorer_navigation(sequence_index);
CREATE INDEX idx_quest_explorer_nav_previous_navigation ON quest_explorer_navigation_previous_entries(navigation_id);
CREATE INDEX idx_quest_explorer_nav_next_navigation ON quest_explorer_navigation_next_entries(navigation_id);
CREATE INDEX idx_quest_explorer_nav_failure_navigation ON quest_explorer_navigation_failure_entries(navigation_id);
CREATE INDEX idx_quest_explorer_nav_convergence_navigation ON quest_explorer_navigation_convergence_entries(navigation_id);
CREATE INDEX idx_quest_explorer_lore_sections_entry ON quest_explorer_lore_sections(entry_id);
CREATE INDEX idx_quest_explorer_lore_lines_section ON quest_explorer_lore_lines(section_id);
CREATE INDEX idx_quest_explorer_objectives_entry ON quest_explorer_objectives(entry_id);
CREATE INDEX idx_quest_explorer_objective_requirements_objective ON quest_explorer_objective_requirements(objective_id);
CREATE INDEX idx_quest_explorer_objective_rewards_objective ON quest_explorer_objective_rewards(objective_id);
CREATE INDEX idx_quest_explorer_branches_entry ON quest_explorer_branches(entry_id);
CREATE INDEX idx_quest_explorer_branch_next_branch ON quest_explorer_branch_next_entries(branch_id);
CREATE INDEX idx_quest_explorer_branch_failure_branch ON quest_explorer_branch_failure_entries(branch_id);
CREATE INDEX idx_quest_explorer_branch_convergence_branch ON quest_explorer_branch_convergence_entries(branch_id);
CREATE INDEX idx_quest_explorer_branch_preview_branch ON quest_explorer_branch_outcome_preview_lines(branch_id);
CREATE INDEX idx_quest_explorer_branch_conditions_branch ON quest_explorer_branch_conditions(branch_id);
CREATE INDEX idx_quest_explorer_branch_requirements_branch ON quest_explorer_branch_requirements(branch_id);
CREATE INDEX idx_quest_explorer_branch_rewards_branch ON quest_explorer_branch_rewards(branch_id);
