DROP TABLE IF EXISTS quest_dialog_lines;
DROP TABLE IF EXISTS quest_dialog_blocks;
DROP TABLE IF EXISTS quest_steps;
DROP TABLE IF EXISTS quest_choices;
DROP TABLE IF EXISTS quests;

CREATE TABLE quest_chronicle_import_batches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game VARCHAR(120),
    game_version VARCHAR(80),
    exporter_version VARCHAR(80),
    exported_at_utc VARCHAR(80),
    export_kind VARCHAR(80) NOT NULL,
    schema_version VARCHAR(80),
    contract_surface VARCHAR(120),
    imported_at TIMESTAMP NOT NULL
);

CREATE TABLE quest_chronicle_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id BIGINT NOT NULL,
    entry_order INTEGER NOT NULL,
    entry_key VARCHAR(260) NOT NULL,
    primary_quest_key VARCHAR(260),
    source_quest_keys TEXT,
    grouping_key TEXT,
    grouping_reason VARCHAR(220),
    title VARCHAR(500),
    summary_lines TEXT,
    quest_type VARCHAR(160),
    is_mandatory BOOLEAN NOT NULL,
    is_key_narrative_beat BOOLEAN NOT NULL,
    faction_key VARCHAR(260),
    quest_line_key VARCHAR(260),
    chapter INTEGER,
    chapter_label VARCHAR(160),
    step INTEGER,
    step_label VARCHAR(160),
    branch_key VARCHAR(260),
    branch_label VARCHAR(260),
    next_entry_keys TEXT,
    failure_entry_keys TEXT,
    converges_into_entry_keys TEXT,
    CONSTRAINT fk_quest_chronicle_entries_batch
        FOREIGN KEY (batch_id) REFERENCES quest_chronicle_import_batches(id) ON DELETE CASCADE,
    CONSTRAINT uq_quest_chronicle_entries_entry_key UNIQUE (entry_key)
);

CREATE TABLE quest_chronicle_source_aliases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entry_id BIGINT NOT NULL,
    alias_order INTEGER NOT NULL,
    source_quest_key VARCHAR(260) NOT NULL,
    CONSTRAINT fk_quest_chronicle_source_aliases_entry
        FOREIGN KEY (entry_id) REFERENCES quest_chronicle_entries(id) ON DELETE CASCADE,
    CONSTRAINT uq_quest_chronicle_source_aliases_entry_key UNIQUE (entry_id, source_quest_key)
);

CREATE TABLE quest_chronicle_objectives (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entry_id BIGINT NOT NULL,
    objective_order INTEGER NOT NULL,
    objective_text TEXT,
    source_quest_key VARCHAR(260),
    choice_key VARCHAR(260),
    step_index INTEGER,
    description_lines TEXT,
    completion_lines TEXT,
    failure_lines TEXT,
    forbidden_lines TEXT,
    selection_lines TEXT,
    reward_lines TEXT,
    CONSTRAINT fk_quest_chronicle_objectives_entry
        FOREIGN KEY (entry_id) REFERENCES quest_chronicle_entries(id) ON DELETE CASCADE
);

CREATE TABLE quest_chronicle_paths (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entry_id BIGINT NOT NULL,
    path_order INTEGER NOT NULL,
    path_key VARCHAR(300) NOT NULL,
    label VARCHAR(500),
    label_source VARCHAR(160),
    choice_ordinal INTEGER,
    source_quest_key VARCHAR(260),
    choice_key VARCHAR(260),
    condition_lines TEXT,
    reward_lines TEXT,
    next_entry_keys TEXT,
    failure_entry_keys TEXT,
    CONSTRAINT fk_quest_chronicle_paths_entry
        FOREIGN KEY (entry_id) REFERENCES quest_chronicle_entries(id) ON DELETE CASCADE
);

CREATE TABLE quest_chronicle_requirements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_type VARCHAR(40) NOT NULL,
    owner_id BIGINT NOT NULL,
    requirement_order INTEGER NOT NULL,
    requirement_key TEXT,
    kind VARCHAR(160),
    phase VARCHAR(80),
    polarity VARCHAR(80),
    display_text TEXT,
    reference_key VARCHAR(260),
    reference_kind VARCHAR(160),
    reference_display_name VARCHAR(500),
    target_role VARCHAR(160),
    target_label VARCHAR(500),
    state VARCHAR(160),
    required_count INTEGER,
    duration_turns INTEGER
);

CREATE TABLE quest_chronicle_rewards (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_type VARCHAR(40) NOT NULL,
    owner_id BIGINT NOT NULL,
    reward_order INTEGER NOT NULL,
    reward_key TEXT,
    source_reward_keys TEXT,
    kind VARCHAR(160),
    display_text TEXT,
    formula_text TEXT,
    amount INTEGER,
    asset_kind VARCHAR(160),
    asset_key VARCHAR(260),
    asset_display_name VARCHAR(500),
    target_scope_label VARCHAR(260)
);

CREATE TABLE quest_chronicle_transcript_blocks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entry_id BIGINT NOT NULL,
    block_order INTEGER NOT NULL,
    dialog_key VARCHAR(260),
    phase VARCHAR(100),
    source_quest_key VARCHAR(260),
    choice_key VARCHAR(260),
    step_index INTEGER,
    CONSTRAINT fk_quest_chronicle_transcript_blocks_entry
        FOREIGN KEY (entry_id) REFERENCES quest_chronicle_entries(id) ON DELETE CASCADE
);

CREATE TABLE quest_chronicle_transcript_lines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transcript_block_id BIGINT NOT NULL,
    line_order INTEGER NOT NULL,
    line_index INTEGER,
    role VARCHAR(100),
    speaker_label VARCHAR(260),
    text TEXT,
    CONSTRAINT fk_quest_chronicle_transcript_lines_block
        FOREIGN KEY (transcript_block_id) REFERENCES quest_chronicle_transcript_blocks(id) ON DELETE CASCADE
);

CREATE INDEX idx_quest_chronicle_entries_batch ON quest_chronicle_entries(batch_id);
CREATE INDEX idx_quest_chronicle_source_aliases_key ON quest_chronicle_source_aliases(source_quest_key);
CREATE INDEX idx_quest_chronicle_objectives_entry ON quest_chronicle_objectives(entry_id);
CREATE INDEX idx_quest_chronicle_paths_entry ON quest_chronicle_paths(entry_id);
CREATE INDEX idx_quest_chronicle_requirements_owner ON quest_chronicle_requirements(owner_type, owner_id);
CREATE INDEX idx_quest_chronicle_rewards_owner ON quest_chronicle_rewards(owner_type, owner_id);
CREATE INDEX idx_quest_chronicle_transcript_blocks_entry ON quest_chronicle_transcript_blocks(entry_id);
CREATE INDEX idx_quest_chronicle_transcript_lines_block ON quest_chronicle_transcript_lines(transcript_block_id);
