CREATE TABLE IF NOT EXISTS factions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    faction_key VARCHAR(255) NOT NULL,
    public_display_name VARCHAR(255) NOT NULL,
    lore TEXT,
    faction_kind VARCHAR(120),
    affinity_key VARCHAR(255),
    affinity_type VARCHAR(120),
    trait_keys TEXT,
    population_keys TEXT,
    unit_keys TEXT,
    base_unit_keys TEXT,
    hero_keys TEXT,
    gated_technology_keys TEXT,
    starting_faction_quest_key VARCHAR(255),
    specific_quest_keys TEXT,
    protectorate_trait_keys TEXT,
    CONSTRAINT uq_factions_faction_key UNIQUE (faction_key)
);

CREATE INDEX IF NOT EXISTS ix_factions_faction_key ON factions(faction_key);
