CREATE TABLE IF NOT EXISTS rich_heroes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    unit_key VARCHAR(255) NOT NULL,
    display_name VARCHAR(255) NOT NULL,
    faction VARCHAR(255),
    faction_key VARCHAR(255),
    is_major_faction BOOLEAN,
    hero_key VARCHAR(255),
    hero_class_key VARCHAR(255),
    origin_kind VARCHAR(120),
    origin_faction_key VARCHAR(255),
    minor_faction_key VARCHAR(255),
    unit_class_key VARCHAR(255),
    attack_skill_key VARCHAR(255),
    own_ability_keys TEXT,
    ability_keys TEXT,
    combat_ability_keys TEXT,
    tactical_ability_keys TEXT,
    passive_ability_keys TEXT,
    mechanical_ability_keys TEXT,
    class_rule_ability_keys TEXT,
    hidden_helper_ability_keys TEXT,
    default_skill_keys TEXT,
    applicable_skill_tree_keys TEXT,
    description_lines TEXT,
    reference_keys TEXT,
    CONSTRAINT uq_rich_heroes_unit_key UNIQUE (unit_key)
);

CREATE INDEX IF NOT EXISTS ix_rich_heroes_unit_key ON rich_heroes(unit_key);

CREATE TABLE IF NOT EXISTS hero_skill_trees (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tree_key VARCHAR(255) NOT NULL,
    tree_type VARCHAR(120),
    is_hidden BOOLEAN,
    tier_placement_keys TEXT,
    tier_keys TEXT,
    skill_keys TEXT,
    reference_keys TEXT,
    class_prerequisite_key VARCHAR(255),
    faction_prerequisite_key VARCHAR(255),
    CONSTRAINT uq_hero_skill_trees_tree_key UNIQUE (tree_key)
);

CREATE INDEX IF NOT EXISTS ix_hero_skill_trees_tree_key ON hero_skill_trees(tree_key);

CREATE TABLE IF NOT EXISTS hero_skill_tiers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tier_placement_key VARCHAR(255) NOT NULL,
    tier_key VARCHAR(255),
    tree_key VARCHAR(255),
    tree_type VARCHAR(120),
    tier_index INTEGER,
    level_prerequisite INTEGER,
    skill_keys TEXT,
    reference_keys TEXT,
    CONSTRAINT uq_hero_skill_tiers_placement UNIQUE (tier_placement_key)
);

CREATE INDEX IF NOT EXISTS ix_hero_skill_tiers_placement ON hero_skill_tiers(tier_placement_key);

CREATE TABLE IF NOT EXISTS hero_skills (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    skill_key VARCHAR(255) NOT NULL,
    entry_key VARCHAR(255),
    kind VARCHAR(120),
    display_name VARCHAR(255),
    public_display_name VARCHAR(255),
    primary_ability_key VARCHAR(255),
    description_lines TEXT,
    resolved_display_name VARCHAR(255),
    resolved_summary_lines TEXT,
    resolved_mechanic_kind VARCHAR(120),
    resolved_mechanic_tags TEXT,
    is_obsolete BOOLEAN,
    is_active BOOLEAN,
    is_passive BOOLEAN,
    placements TEXT,
    prerequisite_skill_keys TEXT,
    inhibited_by_skill_keys TEXT,
    locked_by_skill_keys TEXT,
    effects TEXT,
    unit_ability_keys TEXT,
    battle_skill_keys TEXT,
    battle_ability_keys TEXT,
    descriptor_keys TEXT,
    unit_ability_event_keys TEXT,
    reward_per_kill_in_battle_effect_keys TEXT,
    stat_affinity_names TEXT,
    default_for_hero_keys TEXT,
    reference_keys TEXT,
    CONSTRAINT uq_hero_skills_skill_key UNIQUE (skill_key)
);

CREATE INDEX IF NOT EXISTS ix_hero_skills_skill_key ON hero_skills(skill_key);

CREATE TABLE IF NOT EXISTS hero_skill_defaults (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hero_key VARCHAR(255) NOT NULL,
    default_skill_keys TEXT,
    reference_keys TEXT,
    faction_key VARCHAR(255),
    class_key VARCHAR(255),
    CONSTRAINT uq_hero_skill_defaults_hero_key UNIQUE (hero_key)
);

CREATE INDEX IF NOT EXISTS ix_hero_skill_defaults_hero_key ON hero_skill_defaults(hero_key);
