CREATE TABLE import_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_key VARCHAR(80) NOT NULL,
    trigger VARCHAR(80) NOT NULL,
    status VARCHAR(80) NOT NULL,
    started_at_utc TIMESTAMP NOT NULL,
    completed_at_utc TIMESTAMP NOT NULL,
    source_label VARCHAR(260),
    profile VARCHAR(160),
    file_count INTEGER NOT NULL DEFAULT 0,
    imported_file_count INTEGER NOT NULL DEFAULT 0,
    skipped_file_count INTEGER NOT NULL DEFAULT 0,
    failed_file_count INTEGER NOT NULL DEFAULT 0,
    received_count INTEGER NOT NULL DEFAULT 0,
    inserted_count INTEGER NOT NULL DEFAULT 0,
    updated_count INTEGER NOT NULL DEFAULT 0,
    unchanged_count INTEGER NOT NULL DEFAULT 0,
    deleted_count INTEGER NOT NULL DEFAULT 0,
    failed_count INTEGER NOT NULL DEFAULT 0,
    game VARCHAR(120),
    game_version VARCHAR(120),
    exporter_version VARCHAR(120),
    exported_at_utc VARCHAR(120),
    notes TEXT,
    CONSTRAINT uq_import_runs_run_key UNIQUE (run_key)
);

CREATE TABLE import_file_results (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    import_run_id BIGINT NOT NULL,
    file_order INTEGER NOT NULL,
    folder VARCHAR(80),
    filename VARCHAR(500) NOT NULL,
    source_path_hash VARCHAR(64),
    file_sha256 VARCHAR(64),
    export_kind VARCHAR(160),
    import_kind VARCHAR(160),
    game VARCHAR(120),
    game_version VARCHAR(120),
    exporter_version VARCHAR(120),
    exported_at_utc VARCHAR(120),
    schema_version VARCHAR(160),
    status VARCHAR(80) NOT NULL,
    skip_reason VARCHAR(260),
    error_message TEXT,
    received_count INTEGER NOT NULL DEFAULT 0,
    inserted_count INTEGER NOT NULL DEFAULT 0,
    updated_count INTEGER NOT NULL DEFAULT 0,
    unchanged_count INTEGER NOT NULL DEFAULT 0,
    deleted_count INTEGER NOT NULL DEFAULT 0,
    failed_count INTEGER NOT NULL DEFAULT 0,
    duration_ms BIGINT,
    CONSTRAINT fk_import_file_results_run
        FOREIGN KEY (import_run_id) REFERENCES import_runs(id) ON DELETE CASCADE
);

CREATE INDEX idx_import_runs_completed_at ON import_runs(completed_at_utc);
CREATE INDEX idx_import_file_results_run ON import_file_results(import_run_id);
