SET CONSTRAINTS ALL DEFERRED;

INSERT INTO "public"."improvements" ("era", "name", "unique_type") VALUES (1, 'Traveler''s Shrine', 'CITY');
INSERT INTO "public"."improvements" ("era", "name", "unique_type") VALUES (2, 'Garrison', 'CITY');
INSERT INTO "public"."improvements" ("era", "name", "unique_type") VALUES (2, 'Legion Vaults', 'EMPIRE');
INSERT INTO "public"."improvements" ("era", "name", "unique_type") VALUES (2, 'Scriptorium', 'CITY');
INSERT INTO "public"."improvements" ("era", "name", "unique_type") VALUES (2, 'Lodgings', 'CITY');
INSERT INTO "public"."improvements" ("era", "name", "unique_type") VALUES (2, 'Emergency Dwellings', 'CITY');
INSERT INTO "public"."improvements" ("era", "name", "unique_type") VALUES (2, 'Laborer''s Hut', 'CITY');
INSERT INTO "public"."improvements" ("era", "name", "unique_type") VALUES (2, 'Granary', 'EMPIRE');
INSERT INTO "public"."improvements" ("era", "name", "unique_type") VALUES (2, 'Blast Furnace', 'CITY');
INSERT INTO "public"."improvements" ("era", "name", "unique_type") VALUES (2, 'Lithosphere Gallery', 'CITY');
INSERT INTO "public"."improvements" ("era", "name", "unique_type") VALUES (2, 'Geodesic Dome', 'CITY');
INSERT INTO "public"."improvements" ("era", "name", "unique_type") VALUES (2, 'Beacon of Science', 'EMPIRE');
INSERT INTO "public"."improvements" ("era", "name", "unique_type") VALUES (2, 'Hydropump', 'EMPIRE');
INSERT INTO "public"."improvements" ("era", "name", "unique_type") VALUES (3, 'Military Efficiency', 'EMPIRE');
INSERT INTO "public"."improvements" ("era", "name", "unique_type") VALUES (3, 'Legionaries Workshop', 'CITY');
INSERT INTO "public"."improvements" ("era", "name", "unique_type") VALUES (3, 'Halls of Power', 'CITY');
INSERT INTO "public"."improvements" ("era", "name", "unique_type") VALUES (3, 'Citizen''s Center', 'CITY');
INSERT INTO "public"."improvements" ("era", "name", "unique_type") VALUES (3, 'Irrigation Channels', 'CITY');
INSERT INTO "public"."improvements" ("era", "name", "unique_type") VALUES (3, 'Wood Ash Pit', 'CITY');
INSERT INTO "public"."improvements" ("era", "name", "unique_type") VALUES (3, 'Spire of Industry', 'EMPIRE');
INSERT INTO "public"."improvements" ("era", "name", "unique_type") VALUES (3, 'Corkscrew Drill', 'CITY');
INSERT INTO "public"."improvements" ("era", "name", "unique_type") VALUES (3, 'Alchemists'' Commission', 'CITY');
INSERT INTO "public"."improvements" ("era", "name", "unique_type") VALUES (3, 'Caravanserai', 'CITY');
INSERT INTO "public"."improvements" ("era", "name", "unique_type") VALUES (3, 'Lumber Yard', 'CITY');
INSERT INTO "public"."improvements" ("era", "name", "unique_type") VALUES (3, 'Dust Blasting', 'EMPIRE');
INSERT INTO "public"."improvements" ("era", "name", "unique_type") VALUES (3, 'Research Station', 'CITY');
INSERT INTO "public"."improvements" ("era", "name", "unique_type") VALUES (3, 'Wildlife Lookout', 'CITY');
INSERT INTO "public"."improvements" ("era", "name", "unique_type") VALUES (4, 'Commanders'' Table', 'CITY');
INSERT INTO "public"."improvements" ("era", "name", "unique_type") VALUES (4, 'Watchman''s Bell', 'CITY');
INSERT INTO "public"."improvements" ("era", "name", "unique_type") VALUES (4, 'Martial Discipline', 'CITY');
INSERT INTO "public"."improvements" ("era", "name", "unique_type") VALUES (4, 'Museum', 'CITY');
INSERT INTO "public"."improvements" ("era", "name", "unique_type") VALUES (4, 'Parade Stands', 'CITY');
INSERT INTO "public"."improvements" ("era", "name", "unique_type") VALUES (4, 'Windmill', 'CITY');
INSERT INTO "public"."improvements" ("era", "name", "unique_type") VALUES (4, 'Farming Cooperative', 'CITY');
INSERT INTO "public"."improvements" ("era", "name", "unique_type") VALUES (4, 'Workers'' League', 'CITY');
INSERT INTO "public"."improvements" ("era", "name", "unique_type") VALUES (4, 'Artisans'' Tools', 'CITY');
INSERT INTO "public"."improvements" ("era", "name", "unique_type") VALUES (4, 'Thermal Baths', 'EMPIRE');
INSERT INTO "public"."improvements" ("era", "name", "unique_type") VALUES (4, 'Lined Crates', 'CITY');
INSERT INTO "public"."improvements" ("era", "name", "unique_type") VALUES (4, 'Scientific Repository', 'EMPIRE');
INSERT INTO "public"."improvements" ("era", "name", "unique_type") VALUES (4, 'Quarry Oversight', 'EMPIRE');
INSERT INTO "public"."improvements" ("era", "name", "unique_type") VALUES (4, 'Fish Farms', 'CITY');
INSERT INTO "public"."improvements" ("era", "name", "unique_type") VALUES (5, 'Fortified Cities', 'EMPIRE');
INSERT INTO "public"."improvements" ("era", "name", "unique_type") VALUES (5, 'Protective Carapaces', 'EMPIRE');
INSERT INTO "public"."improvements" ("era", "name", "unique_type") VALUES (5, 'Imperial Secretariat', 'EMPIRE');
INSERT INTO "public"."improvements" ("era", "name", "unique_type") VALUES (5, 'Teahouse', 'EMPIRE');
INSERT INTO "public"."improvements" ("era", "name", "unique_type") VALUES (5, 'Canning Shed', 'EMPIRE');
INSERT INTO "public"."improvements" ("era", "name", "unique_type") VALUES (5, 'Nectar Silo', 'EMPIRE');
INSERT INTO "public"."improvements" ("era", "name", "unique_type") VALUES (5, 'Ore Breaker', 'EMPIRE');
INSERT INTO "public"."improvements" ("era", "name", "unique_type") VALUES (5, 'Land Clearance', 'EMPIRE');
INSERT INTO "public"."improvements" ("era", "name", "unique_type") VALUES (5, 'Cashier''s Lodge', 'EMPIRE');
INSERT INTO "public"."improvements" ("era", "name", "unique_type") VALUES (5, 'Treasury', 'EMPIRE');
INSERT INTO "public"."improvements" ("era", "name", "unique_type") VALUES (5, 'Customs Inspector', 'CITY');
INSERT INTO "public"."improvements" ("era", "name", "unique_type") VALUES (5, 'Collections Bureau', 'CITY');
INSERT INTO "public"."improvements" ("era", "name", "unique_type") VALUES (5, 'Lecture Hall', 'CITY');
INSERT INTO "public"."improvements" ("era", "name", "unique_type") VALUES (5, 'Philosophers'' Circle', 'CITY');
INSERT INTO "public"."improvements" ("era", "name", "unique_type") VALUES (5, 'Grant Treasury', 'EMPIRE');
INSERT INTO "public"."improvements" ("era", "name", "unique_type") VALUES (5, 'Field Studies', 'EMPIRE');
INSERT INTO "public"."improvements" ("era", "name", "unique_type") VALUES (2, 'Fungal Gardens', 'EMPIRE');
INSERT INTO "public"."improvements" ("era", "name", "unique_type") VALUES (2, 'Scavengers Lair', 'EMPIRE');
INSERT INTO "public"."improvements" ("era", "name", "unique_type") VALUES (2, 'Mycology Lab', 'CITY');
INSERT INTO "public"."improvements" ("era", "name", "unique_type") VALUES (3, 'Chitinous Matriach', 'EMPIRE');
INSERT INTO "public"."improvements" ("era", "name", "unique_type") VALUES (4, 'Ocular Evolution', 'EMPIRE');
INSERT INTO "public"."improvements" ("era", "name", "unique_type") VALUES (4, 'Chitin Vats', 'CITY');
INSERT INTO "public"."improvements" ("era", "name", "unique_type") VALUES (4, 'Memory Well', 'CITY');
INSERT INTO "public"."improvements" ("era", "name", "unique_type") VALUES (4, 'Deeper Caverns', 'CITY');
INSERT INTO "public"."improvements" ("era", "name", "unique_type") VALUES (2, 'Mineral Inquisition', 'CITY');
INSERT INTO "public"."improvements" ("era", "name", "unique_type") VALUES (2, 'Dust Divination', 'CITY');
INSERT INTO "public"."improvements" ("era", "name", "unique_type") VALUES (4, 'Knightwatch', 'CITY');
INSERT INTO "public"."improvements" ("era", "name", "unique_type") VALUES (2, 'Celestial Guidance', 'EMPIRE');
INSERT INTO "public"."improvements" ("era", "name", "unique_type") VALUES (4, 'Solar Strobe', 'EMPIRE');
INSERT INTO "public"."improvements" ("era", "name", "unique_type") VALUES (2, 'Consular Mission', 'EMPIRE');
INSERT INTO "public"."improvements" ("era", "name", "unique_type") VALUES (3, 'Hall of Harmony', 'CITY');
INSERT INTO "public"."improvements" ("era", "name", "unique_type") VALUES (4, 'Nutrient Extractor', 'CITY');

-- Reset sequences after insert data
SELECT setval('improvements_id_seq', (SELECT COALESCE(MAX(id),0) FROM "improvements"));