SET CONSTRAINTS ALL DEFERRED;


INSERT INTO "public"."improvement_costs" ("improvement_id", "amount", "resource_type") VALUES (7, 5, 'GLASSTEEL');
INSERT INTO "public"."improvement_costs" ("improvement_id", "amount", "resource_type") VALUES (10, 5, 'GLASSTEEL');
INSERT INTO "public"."improvement_costs" ("improvement_id", "amount", "resource_type") VALUES (11, 5, 'GLASSTEEL');
INSERT INTO "public"."improvement_costs" ("improvement_id", "amount", "resource_type") VALUES (14, 20, 'GLASSTEEL');
INSERT INTO "public"."improvement_costs" ("improvement_id", "amount", "resource_type") VALUES (19, 10, 'GLASSTEEL');
INSERT INTO "public"."improvement_costs" ("improvement_id", "amount", "resource_type") VALUES (20, 20, 'GLASSTEEL');
INSERT INTO "public"."improvement_costs" ("improvement_id", "amount", "resource_type") VALUES (22, 10, 'GLASSTEEL');
INSERT INTO "public"."improvement_costs" ("improvement_id", "amount", "resource_type") VALUES (24, 10, 'GLASSTEEL');
INSERT INTO "public"."improvement_costs" ("improvement_id", "amount", "resource_type") VALUES (25, 20, 'GLASSTEEL');
INSERT INTO "public"."improvement_costs" ("improvement_id", "amount", "resource_type") VALUES (27, 10, 'GLASSTEEL');
INSERT INTO "public"."improvement_costs" ("improvement_id", "amount", "resource_type") VALUES (39, 5, 'GLASSTEEL');
INSERT INTO "public"."improvement_costs" ("improvement_id", "amount", "resource_type") VALUES (39, 5, 'HYPERIUM');
INSERT INTO "public"."improvement_costs" ("improvement_id", "amount", "resource_type") VALUES (39, 5, 'THALITINE');
INSERT INTO "public"."improvement_costs" ("improvement_id", "amount", "resource_type") VALUES (40, 5, 'GLASSTEEL');
INSERT INTO "public"."improvement_costs" ("improvement_id", "amount", "resource_type") VALUES (40, 5, 'HYPERIUM');
INSERT INTO "public"."improvement_costs" ("improvement_id", "amount", "resource_type") VALUES (40, 5, 'THALITINE');
INSERT INTO "public"."improvement_costs" ("improvement_id", "amount", "resource_type") VALUES (43, 5, 'GLASSTEEL');
INSERT INTO "public"."improvement_costs" ("improvement_id", "amount", "resource_type") VALUES (43, 5, 'HYPERIUM');
INSERT INTO "public"."improvement_costs" ("improvement_id", "amount", "resource_type") VALUES (43, 5, 'THALITINE');
INSERT INTO "public"."improvement_costs" ("improvement_id", "amount", "resource_type") VALUES (44, 5, 'TITANIUM');
INSERT INTO "public"."improvement_costs" ("improvement_id", "amount", "resource_type") VALUES (45, 5, 'GLASSTEEL');
INSERT INTO "public"."improvement_costs" ("improvement_id", "amount", "resource_type") VALUES (45, 5, 'HYPERIUM');
INSERT INTO "public"."improvement_costs" ("improvement_id", "amount", "resource_type") VALUES (45, 5, 'THALITINE');
INSERT INTO "public"."improvement_costs" ("improvement_id", "amount", "resource_type") VALUES (46, 5, 'GLASSTEEL');
INSERT INTO "public"."improvement_costs" ("improvement_id", "amount", "resource_type") VALUES (46, 5, 'HYPERIUM');
INSERT INTO "public"."improvement_costs" ("improvement_id", "amount", "resource_type") VALUES (46, 5, 'THALITINE');
INSERT INTO "public"."improvement_costs" ("improvement_id", "amount", "resource_type") VALUES (47, 5, 'GLASSTEEL');
INSERT INTO "public"."improvement_costs" ("improvement_id", "amount", "resource_type") VALUES (47, 5, 'HYPERIUM');
INSERT INTO "public"."improvement_costs" ("improvement_id", "amount", "resource_type") VALUES (47, 5, 'THALITINE');
INSERT INTO "public"."improvement_costs" ("improvement_id", "amount", "resource_type") VALUES (48, 5, 'GLASSTEEL');
INSERT INTO "public"."improvement_costs" ("improvement_id", "amount", "resource_type") VALUES (48, 5, 'HYPERIUM');
INSERT INTO "public"."improvement_costs" ("improvement_id", "amount", "resource_type") VALUES (48, 5, 'THALITINE');
INSERT INTO "public"."improvement_costs" ("improvement_id", "amount", "resource_type") VALUES (49, 5, 'GLASSTEEL');
INSERT INTO "public"."improvement_costs" ("improvement_id", "amount", "resource_type") VALUES (49, 5, 'HYPERIUM');
INSERT INTO "public"."improvement_costs" ("improvement_id", "amount", "resource_type") VALUES (49, 5, 'THALITINE');
INSERT INTO "public"."improvement_costs" ("improvement_id", "amount", "resource_type") VALUES (50, 5, 'GLASSTEEL');
INSERT INTO "public"."improvement_costs" ("improvement_id", "amount", "resource_type") VALUES (50, 5, 'HYPERIUM');
INSERT INTO "public"."improvement_costs" ("improvement_id", "amount", "resource_type") VALUES (50, 5, 'THALITINE');
INSERT INTO "public"."improvement_costs" ("improvement_id", "amount", "resource_type") VALUES (51, 5, 'GLASSTEEL');
INSERT INTO "public"."improvement_costs" ("improvement_id", "amount", "resource_type") VALUES (51, 5, 'HYPERIUM');
INSERT INTO "public"."improvement_costs" ("improvement_id", "amount", "resource_type") VALUES (51, 5, 'THALITINE');
INSERT INTO "public"."improvement_costs" ("improvement_id", "amount", "resource_type") VALUES (56, 5, 'GLASSTEEL');
INSERT INTO "public"."improvement_costs" ("improvement_id", "amount", "resource_type") VALUES (56, 5, 'HYPERIUM');
INSERT INTO "public"."improvement_costs" ("improvement_id", "amount", "resource_type") VALUES (56, 5, 'THALITINE');
INSERT INTO "public"."improvement_costs" ("improvement_id", "amount", "resource_type") VALUES (57, 5, 'GLASSTEEL');
INSERT INTO "public"."improvement_costs" ("improvement_id", "amount", "resource_type") VALUES (57, 5, 'HYPERIUM');
INSERT INTO "public"."improvement_costs" ("improvement_id", "amount", "resource_type") VALUES (57, 5, 'THALITINE');
INSERT INTO "public"."improvement_costs" ("improvement_id", "amount", "resource_type") VALUES (68, 20, 'GLASSTEEL');
INSERT INTO "public"."improvement_costs" ("improvement_id", "amount", "resource_type") VALUES (68, 10, 'HYPERIUM');

INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (1, '+15 Approval');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (2, '+500 District Fortification');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (3, '+200 District Fortification');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (3, '+50 Health on Militia');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (3, '+10 Defense on on Militia');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (4, '+5 Influence');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (4, '+2 Influence per Population on Scribes');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (6, '+15 Approval');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (6, '+1 Attachable Territory on City');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (6, '+4 Influence on City Hall');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (6, '+4 Influence on Ministry');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (7, '+5 Food');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (7, '+5 Food on Farms Districts');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (8, '+5 Food per Population on Citizens');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (8, '+3 Population slot on Citizen');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (9, '+25 Industry');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (10, '+50 Dust');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (11, '+5 Science');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (11, '+5 Science on Laboratory');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (12, '+10 Science');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (12, '+4 Science per Population on Scribes');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (12, '+3 Population slot on Scribes');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (13, '+5 Industry if adjacent to River on district');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (13, '+5 Dust if adjacent to River on district');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (14, '+100 Experience on new Units on City');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (14, '-3 Dust upkeep on Unit');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (14, '-25% Industry cost on Military Districts');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (16, '+5 Influence');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (16, '+5 influence on District if Forum');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (17, '+1 attachable Territory on City');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (17, '+20 Approval on City');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (18, '+10 Food on Farm Districts if adjacent to River');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (19, '+100% Food on Foundation ');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (20, '+25 Industry');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (20, '+4 Industry per Population on Artisans');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (20, '+3 Population slot on Artisans');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (20, '+20 Resource stock');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (21, '+1 Exploited Resource on Mine');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (22, '+100 Dust on Foundation');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (23, '+10 Dust per adjacent Territory with Trading Post');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (24, '+100% Industry on Foundation');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (25, '+2 Dust on Population');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (25, '+2 Population slot on Population Vocations');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (25, '-25% Buyout cost on District');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (25, '-25% Buyout cost on Improvement');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (25, '-25% Buyout cost on Unit');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (26, '+8 Science to Laboratory if adjacent to Anomaly');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (27, '+100% Science on Foundation');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (28, '+2 Approval per Population on Scribes');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (28, '-1 Influence per Population on Scribes');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (29, '+1 Approval per Population on Citizens');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (29, '-1 Dust per Population on Citizens');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (29, '+1 Approval per Population on Artisans');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (29, '-1 Dust per Population on Artisans');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (30, '+10% Food on City');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (30, '+10% Industry on City');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (30, '+10% Influence on City');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (30, '+10% Dust on City');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (30, '+10% Science on City');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (31, '+1 Influence per Population on Citizens');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (31, '-1 Dust per Population on Citizens');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (31, '+1 Influence per Population on Artisans');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (31, '-1 Dust per Population on Artisans');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (32, '-1 Approval per Population on Scribes');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (32, '+2 Influence per Population on Scribes');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (33, '+2 Food per Population on Citizens');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (33, '-1 Dust per Population on Citizens');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (34, '-1 Approval per Population on Citizens');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (34, '+2 Food per Population on Citizens');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (35, '-1 Approval per Population on Artisans');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (35, '+2 Industry per Population on Artisans');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (36, '+2 Industry per Population on Artisans');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (36, '-1 Dust per Population on Artisans');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (37, '+18 Approval');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (37, '-25% Food consumption on Population');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (37, '+2 Food per Population on Citizens');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (37, '+2 Industry per Population on Artisans');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (37, '+2 Influence per Population on Scribes');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (37, '+5 Population slot on Population Vocations');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (38, '+3 exploited Resource Production on Quarry');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (39, '+2 Science on Trading Post');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (39, '-25% Dust when purchasing Resources on Empire');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (40, '+50 Dust on Quarry');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (41, '+3 Food on River');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (41, '+5 Dust on River if active Monsoon');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (42, '+Approval per City level');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (42, '+50% Fortification on City');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (43, '+500 District Fortification on District');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (43, '+20 Health Regenration on Unit');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (43, '-25% Industry on Unit');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (44, '+4 Influence per City level');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (45, '+15% Influence income on City');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (46, '+9 Approval per City level');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (46, '+5 Food per City level');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (47, '+100 Food Stock capacity on City');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (47, '-25% cost to grow all Populations');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (48, '+10 Industry per City level');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (49, '-25% Industry cost on District');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (49, '-15% Industry cost on Improvement');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (50, '+10 Dust per City level');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (51, '+2 Dust on Trading Post');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (51, '+25% Dust when selling Resources on Empire');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (52, '+2 Dust per population on Citizens');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (52, '-1 Approval per Population on Citizens');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (52, '-1 Approval per Population on Artisans');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (52, '+2 Dust per population on Artisans');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (53, '-1 Approval per Population on Scribes');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (53, '+3 Dust per population on Scribes');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (53, '-1 Approval per Population on Artisans');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (53, '-1 Approval per Population on Citizens');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (54, '-1 Dust per Population on Scribes');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (54, '+2 Science per Population on Scribes');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (55, '-1 Approval per Population on Scribes');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (55, '+2 Science per Population on Scribes');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (56, '+10 Science per City level');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (57, '-15% on all Technology research cost');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (58, '+20 Food');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (58, '´20 Industry');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (58, '+10 Influence');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (58, '+400 Fortification on City');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (58, '+1 Population Slot on Population Vocations');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (59, '+25 Health Regeneration on Units in allied Territory');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (59, '+1 Movement Points outside battle on Unit');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (59, '+10 Dust income on District');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (60, '+5 Health Regeneration on Unit');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (60, '+10 Food on City');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (61, '+10 Influence');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (61, '+20 Dust');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (61, '+20 Science');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (61, '+400 Fortification on City');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (61, '+1 Population Slot on Population Vocations');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (62, '+20 Food');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (62, '+20 Industry');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (62, '+10 Influence');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (62, '+20 Dust');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (62, '+20 Science');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (62, '+400 Fortification on City');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (62, '+1 Population Slot on Population Vocations');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (63, '+5 Industry per Territory on City');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (63, '+5 Industry on City');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (64, '+5 Science per Territory on City');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (64, '+5 Science on City');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (65, '+5 Dust per Territory on City');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (65, '+10 Dust on City');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (65, '-50% Dust on Burrow cost on Empire');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (66, '+15 Science on Extractor');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (67, '+5 Dust on Merchant''s House Districts');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (67, '+1 Dust on Tiles not producing Dust');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (68, '+1 Approval per Population on Citizens');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (69, '+1 Science on Population');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (70, '+3 Populator slot on Scribes');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (70, '+2 Science on Scribes');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (70, '-25% Food consumption on Cities');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (71, '+20% Approval');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (71, '-25% Influence cost on Treaties');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (72, '+1 Influence on Corals in City''s Territories');
INSERT INTO "public"."improvement_effects" ("improvement_id", "effect") VALUES (73, '-15% Food consumption on Population');
