SET CONSTRAINTS ALL DEFERRED;


INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (1, 80, 'INDUSTRY', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (2, 180, 'INDUSTRY', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (3, 450, 'INDUSTRY', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (4, 0, 'INDUSTRY', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (5, 0, 'INDUSTRY', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (6, 0, 'INDUSTRY', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (7, 180, 'INDUSTRY', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (8, 300, 'INDUSTRY', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (9, 5, null, 'TITANIUM');
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (9, 100, 'DUST', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (10, 10, null, 'TITANIUM');
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (11, 200, 'DUST', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (12, 15, null, 'TITANIUM');
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (13, 200, 'DUST', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (14, 15, null, 'TITANIUM');
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (15, 400, 'DUST', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (16, 15, null, 'LAZUALIN');
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (17, 10, null, 'TITANIUM');
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (17, 300, 'DUST', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (18, 20, null, 'TITANIUM');
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (19, 400, 'DUST', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (20, 15, null, 'LAZUALIN');
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (21, 400, 'DUST', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (22, 15, null, 'LAZUALIN');
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (23, 600, 'DUST', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (24, 15, null, 'ERADIONE');
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (25, 80, 'INDUSTRY', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (26, 180, 'INDUSTRY', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (27, 300, 'INDUSTRY', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (28, 450, 'INDUSTRY', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (29, 200, 'DUST', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (30, 15, null, 'TITANIUM');
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (31, 200, 'DUST', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (32, 15, null, 'TITANIUM');
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (33, 400, 'DUST', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (34, 15, null, 'LAZUALIN');
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (35, 600, 'DUST', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (36, 20, null, 'LAZUALIN');
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (37, 300, 'DUST', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (38, 15, null, 'LAZUALIN');
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (39, 400, 'DUST', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (40, 15, null, 'LAZUALIN');
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (41, 600, 'DUST', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (42, 15, null, 'ERADIONE');
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (43, 1000, 'INDUSTRY', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (44, 20, null, 'ERADIONE');
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (45, 80, 'INDUSTRY', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (46, 180, 'INDUSTRY', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (47, 180, 'INDUSTRY', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (48, 450, 'INDUSTRY', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (49, 100, 'DUST', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (50, 10, null, 'TITANIUM');
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (51, 200, 'DUST', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (52, 15, null, 'TITANIUM');
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (53, 0, 'INDUSTRY', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (54, 200, 'DUST', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (55, 20, null, 'LAZUALIN');
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (56, 600, 'DUST', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (57, 20, null, 'LAZUALIN');
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (58, 300, 'DUST', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (59, 15, null, 'LAZUALIN');
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (60, 400, 'DUST', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (61, 15, null, 'LAZUALIN');
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (62, 400, 'DUST', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (63, 20, null, 'ERADIONE');
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (64, 1000, 'DUST', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (65, 20, null, 'ERADIONE');
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (66, 80, 'INDUSTRY', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (67, 180, 'INDUSTRY', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (68, 300, 'INDUSTRY', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (69, 450, 'INDUSTRY', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (70, 100, 'DUST', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (71, 10, null, 'TITANIUM');
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (72, 200, 'DUST', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (73, 15, null, 'TITANIUM');
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (74, 400, 'DUST', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (75, 15, null, 'LAZUALIN');
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (76, 600, 'DUST', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (77, 20, null, 'LAZUALIN');
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (78, 300, 'DUST', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (79, 15, null, 'LAZUALIN');
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (80, 400, 'DUST', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (81, 15, null, 'LAZUALIN');
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (82, 600, 'DUST', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (83, 15, null, 'ERADIONE');
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (84, 1000, 'DUST', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (85, 20, null, 'ERADIONE');
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (86, 80, 'INDUSTRY', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (87, 20, 'CORPSES', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (88, 20, 'CORPSES', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (89, 20, 'CORPSES', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (90, 30, 'CORPSES', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (90, 200, 'DUST', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (91, 30, 'CORPSES', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (91, 10, null, 'TITANIUM');
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (92, 30, 'CORPSES', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (92, 10, null, 'TITANIUM');
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (93, 30, 'CORPSES', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (93, 300, 'DUST', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (94, 50, 'CORPSES', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (94, 10, null, 'TITANIUM');
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (95, 40, 'CORPSES', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (95, 300, 'DUST', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (96, 40, 'CORPSES', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (96, 10, null, 'LAZUALIN');
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (97, 50, 'CORPSES', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (97, 10, null, 'ERADIONE');
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (98, 40, 'CORPSES', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (98, 500, 'DUST', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (99, 50, 'CORPSES', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (99, 500, 'DUST', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (100, 75, 'CORPSES', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (100, 15, null, 'LAZUALIN');
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (101, 75, 'CORPSES', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (101, 15, null, 'ERADIONE');
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (102, 0, 'INDUSTRY', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (103, 0, 'INDUSTRY', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (104, 0, 'INDUSTRY', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (105, 0, 'INDUSTRY', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (106, 0, 'INDUSTRY', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (107, 0, 'INDUSTRY', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (108, 0, 'INDUSTRY', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (109, 0, 'INDUSTRY', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (110, 0, 'INDUSTRY', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (111, 0, 'INDUSTRY', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (112, 0, 'INDUSTRY', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (113, 0, 'INDUSTRY', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (114, 0, 'INDUSTRY', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (115, 0, 'INDUSTRY', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (116, 0, 'INDUSTRY', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (117, 0, 'INDUSTRY', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (118, 0, 'INDUSTRY', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (119, 0, 'INDUSTRY', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (120, 0, 'INDUSTRY', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (121, 0, 'INDUSTRY', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (122, 0, 'INDUSTRY', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (123, 0, 'INDUSTRY', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (124, 0, 'INDUSTRY', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (125, 0, 'INDUSTRY', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (126, 0, 'INDUSTRY', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (127, 0, 'INDUSTRY', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (128, 0, 'INDUSTRY', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (129, 0, 'INDUSTRY', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (130, 0, 'INDUSTRY', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (131, 0, 'INDUSTRY', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (132, 0, 'INDUSTRY', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (133, 0, 'INDUSTRY', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (134, 0, 'INDUSTRY', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (135, 0, 'INDUSTRY', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (136, 0, 'INDUSTRY', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (137, 0, 'INDUSTRY', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (138, 0, 'INDUSTRY', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (139, 0, 'INDUSTRY', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (140, 0, 'INDUSTRY', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (141, 0, 'INDUSTRY', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (142, 0, 'INDUSTRY', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (143, 0, 'INDUSTRY', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (144, 0, 'INDUSTRY', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (145, 0, 'INDUSTRY', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (146, 0, 'INDUSTRY', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (147, 0, 'INDUSTRY', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (148, 0, 'INDUSTRY', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (149, 0, 'INDUSTRY', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (150, 0, 'INDUSTRY', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (151, 0, 'INDUSTRY', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (152, 0, 'INDUSTRY', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (153, 0, 'INDUSTRY', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (154, 0, 'INDUSTRY', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (155, 0, 'INDUSTRY', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (156, 0, 'INDUSTRY', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (157, 0, 'INDUSTRY', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (158, 0, 'INDUSTRY', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (159, 0, 'INDUSTRY', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (160, 0, 'INDUSTRY', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (161, 0, 'INDUSTRY', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (162, 0, 'INDUSTRY', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (163, 0, 'INDUSTRY', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (164, 0, 'INDUSTRY', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (165, 0, 'INDUSTRY', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (166, 0, 'INDUSTRY', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (167, 0, 'INDUSTRY', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (168, 0, 'INDUSTRY', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (169, 0, 'INDUSTRY', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (170, 0, 'INDUSTRY', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (171, 0, 'INDUSTRY', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (172, 0, 'INDUSTRY', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (173, 0, 'INDUSTRY', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (174, 0, 'INDUSTRY', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (175, 0, 'INDUSTRY', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (176, 0, 'INDUSTRY', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (177, 0, 'INDUSTRY', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (178, 0, 'INDUSTRY', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (179, 0, 'INDUSTRY', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (180, 0, 'INDUSTRY', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (181, 0, 'INDUSTRY', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (182, 0, 'INDUSTRY', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (183, 0, 'INDUSTRY', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (184, 0, 'INDUSTRY', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (185, 0, 'INDUSTRY', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (186, 0, 'INDUSTRY', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (187, 0, 'INDUSTRY', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (188, 0, 'INDUSTRY', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (189, 0, 'INDUSTRY', null);
INSERT INTO "public"."unit_specialization_costs" ("unit_id", "amount", "resource", "strategic") VALUES (190, 0, 'INDUSTRY', null);

INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 62, 1);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 8, 2);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 47, 2);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 5, 3);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 5, 4);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 57, 4);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 5, 5);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 57, 5);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 63, 5);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 5, 6);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 55, 6);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 63, 6);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 57, 6);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 32, 7);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 18, 7);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 8, 8);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 12, 8);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 62, 9);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 40, 9);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 62, 10);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 43, 10);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 8, 11);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 47, 11);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 21, 12);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 47, 12);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 11, 12);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 29, 13);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 18, 13);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 29, 14);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 18, 14);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 6, 14);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 8, 15);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 12, 15);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 8, 16);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 12, 16);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 25, 16);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 62, 17);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 46, 17);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 62, 18);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 23, 18);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 8, 19);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 45, 19);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 21, 20);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 47, 20);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 12, 20);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 33, 21);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 18, 21);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 29, 22);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 58, 22);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 6, 22);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 8, 23);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 19, 23);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 8, 24);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 12, 24);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 26, 24);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 25, 24);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 62, 25);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 6, 25);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 8, 26);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 50, 26);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 32, 27);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 7, 27);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 34, 28);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 30, 28);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 62, 29);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 6, 29);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 40, 29);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 62, 30);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 6, 30);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 18, 30);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 8, 31);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 50, 31);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 8, 32);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 50, 32);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 15, 32);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 29, 33);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 7, 33);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 32, 34);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 7, 34);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 44, 34);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 34, 35);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 30, 35);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 34, 36);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 54, 36);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 61, 36);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 62, 37);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 6, 37);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 46, 37);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 62, 38);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 6, 38);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 58, 38);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 21, 39);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 50, 39);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 8, 40);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 50, 40);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 59, 40);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 33, 41);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 7, 41);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 32, 42);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 7, 42);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 52, 42);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 34, 43);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 54, 43);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 34, 44);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 54, 44);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 24, 44);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 32, 45);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 62, 45);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 8, 46);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 35, 46);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 32, 47);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 41, 47);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 29, 48);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 56, 48);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 32, 49);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 62, 49);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 40, 49);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 32, 50);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 62, 50);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 25, 50);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 8, 51);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 35, 51);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 8, 52);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 35, 52);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 18, 52);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 29, 53);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 41, 53);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 32, 54);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 64, 54);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 43, 54);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 32, 55);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 41, 55);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 64, 55);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 29, 56);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 31, 56);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 29, 57);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 56, 57);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 52, 57);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 32, 58);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 62, 58);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 46, 58);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 32, 59);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 62, 59);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 26, 59);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 8, 60);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 66, 60);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 8, 61);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 35, 61);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 58, 61);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 33, 62);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 41, 62);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 32, 63);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 41, 63);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 27, 63);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 29, 64);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 29, 65);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 56, 65);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 13, 65);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 62, 66);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 20, 66);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 32, 67);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 15, 67);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 48, 68);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 1, 69);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 62, 70);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 20, 70);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 8, 70);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 8, 70);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 40, 71);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 62, 71);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 20, 71);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 40, 71);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 32, 72);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 15, 72);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 29, 73);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 15, 73);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 48, 74);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 48, 75);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 64, 75);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 1, 76);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 1, 77);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 31, 77);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 62, 78);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 38, 78);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 8, 78);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 46, 79);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 62, 79);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 20, 79);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 46, 79);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 32, 80);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 59, 80);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 33, 81);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 15, 81);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 60, 82);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 48, 83);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 27, 83);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 9, 84);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 1, 85);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 34, 87);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 32, 88);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 67, 89);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 34, 90);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 40, 90);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 34, 91);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 25, 91);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 32, 92);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 6, 92);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 67, 93);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 18, 93);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 16, 94);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 49, 94);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 34, 95);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 46, 95);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 34, 96);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 26, 96);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 29, 97);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 6, 97);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 64, 97);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 67, 98);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 58, 98);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 29, 99);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 6, 99);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 14, 99);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 16, 100);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 49, 100);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 28, 100);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 16, 101);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 49, 101);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 31, 101);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 8, 102);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 56, 102);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 21, 103);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 56, 103);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 21, 104);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 31, 104);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 36, 105);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 36, 106);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 8, 106);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 36, 107);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 21, 107);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 51, 108);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 51, 109);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 18, 109);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 51, 110);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 58, 110);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 17, 111);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 17, 112);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 35, 112);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 42, 113);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 35, 113);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 53, 114);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 53, 115);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 6, 115);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 39, 116);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 6, 116);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 3, 117);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 3, 118);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 25, 118);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 3, 119);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 26, 119);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 32, 120);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 12, 120);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 29, 121);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 12, 121);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 29, 122);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 19, 122);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 10, 123);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 10, 124);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 10, 125);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 25, 125);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 10, 126);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 26, 126);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 32, 127);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 64, 127);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 29, 128);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 64, 128);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 29, 129);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 27, 129);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 32, 130);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 2, 130);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 32, 131);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 2, 131);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 15, 131);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 32, 132);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 37, 132);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 59, 132);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 50, 133);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 50, 134);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 6, 134);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 24, 135);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 6, 135);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 66, 136);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 66, 137);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 15, 137);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 66, 138);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 59, 138);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 32, 139);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 32, 140);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 25, 140);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 32, 141);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 26, 141);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 32, 142);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 22, 142);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 32, 143);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 4, 143);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 32, 144);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 65, 144);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 8, 145);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 12, 145);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 21, 146);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 12, 146);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 21, 147);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 19, 147);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 51, 148);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 51, 149);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 18, 149);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 51, 150);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 58, 150);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 17, 151);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 17, 152);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 35, 152);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 42, 153);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 35, 153);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 53, 154);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 53, 155);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 6, 155);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 3, 156);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 3, 157);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 25, 157);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 3, 158);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 26, 158);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 32, 159);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 12, 159);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 29, 160);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 12, 160);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 29, 161);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 19, 161);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 10, 162);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 10, 163);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 25, 163);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 10, 164);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 26, 164);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 32, 165);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 64, 165);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 29, 166);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 64, 166);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 29, 167);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 27, 167);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 32, 168);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 2, 168);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 32, 169);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 2, 169);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 15, 169);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 32, 170);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 37, 170);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 59, 170);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 50, 171);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 24, 172);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 6, 172);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 66, 173);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 66, 174);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 15, 174);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 66, 175);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 59, 175);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 32, 176);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 32, 177);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 25, 177);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 32, 178);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 26, 178);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 32, 179);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 22, 179);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 32, 180);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 4, 180);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 32, 181);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 65, 181);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 8, 182);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 12, 182);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 21, 183);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 12, 183);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 21, 184);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 19, 184);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 51, 185);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 51, 186);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 18, 186);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 51, 187);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 58, 187);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 17, 188);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 17, 189);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 35, 189);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 42, 190);
INSERT INTO "public"."unit_specialization_skills" ("level", "skill_id", "unit_id") VALUES (null, 35, 190);
