SET CONSTRAINTS ALL DEFERRED;

INSERT INTO "public"."tech" ("x_pct", "y_pct", "era", "name", "type", "excludes_id", "prereq_id") VALUES (21.3, 29.76, 1, 'Stonework', 'DEFENSE', null, null);
INSERT INTO "public"."tech" ("x_pct", "y_pct", "era", "name", "type", "excludes_id", "prereq_id") VALUES (35.57, 7.25, 1, 'Voice of the Masses', 'SOCIETY', null, null);
INSERT INTO "public"."tech" ("x_pct", "y_pct", "era", "name", "type", "excludes_id", "prereq_id") VALUES (47.4, 16.96, 1, 'Civil Order', 'SOCIETY', null, null);
INSERT INTO "public"."tech" ("x_pct", "y_pct", "era", "name", "type", "excludes_id", "prereq_id") VALUES (59.22, 7.25, 1, 'Fencing', 'SOCIETY', null, null);
INSERT INTO "public"."tech" ("x_pct", "y_pct", "era", "name", "type", "excludes_id", "prereq_id") VALUES (71.09, 29.82, 1, 'Workshop', 'ECONOMY', null, null);
INSERT INTO "public"."tech" ("x_pct", "y_pct", "era", "name", "type", "excludes_id", "prereq_id") VALUES (71.04, 58, 1, 'Currency', 'ECONOMY', null, null);
INSERT INTO "public"."tech" ("x_pct", "y_pct", "era", "name", "type", "excludes_id", "prereq_id") VALUES (56.88, 73.96, 1, 'Keystones', 'DISCOVERY', null, null);
INSERT INTO "public"."tech" ("x_pct", "y_pct", "era", "name", "type", "excludes_id", "prereq_id") VALUES (37.92, 74.06, 1, 'Scientific Charter', 'DISCOVERY', null, null);
INSERT INTO "public"."tech" ("x_pct", "y_pct", "era", "name", "type", "excludes_id", "prereq_id") VALUES (30.78, 42, 1, 'The Strength of Garin', 'DEFENSE', null, null);
INSERT INTO "public"."tech" ("x_pct", "y_pct", "era", "name", "type", "excludes_id", "prereq_id") VALUES (21.3, 58, 1, 'Scavenging', 'DEFENSE', null, null);
INSERT INTO "public"."tech" ("x_pct", "y_pct", "era", "name", "type", "excludes_id", "prereq_id") VALUES (21.3, 29.76, 2, 'Shock Tactics', 'DEFENSE', null, null);
INSERT INTO "public"."tech" ("x_pct", "y_pct", "era", "name", "type", "excludes_id", "prereq_id") VALUES (30.78, 42, 2, 'The Hand of Garin', 'DEFENSE', null, null);
INSERT INTO "public"."tech" ("x_pct", "y_pct", "era", "name", "type", "excludes_id", "prereq_id") VALUES (21.3, 58, 2, 'Sheredyn''s Creed', 'DEFENSE', null, null);
INSERT INTO "public"."tech" ("x_pct", "y_pct", "era", "name", "type", "excludes_id", "prereq_id") VALUES (28.45, 4.3, 2, 'Foreign Affairs', 'SOCIETY', null, null);
INSERT INTO "public"."tech" ("x_pct", "y_pct", "era", "name", "type", "excludes_id", "prereq_id") VALUES (40.28, 23.42, 2, 'Common Rights', 'SOCIETY', null, null);
INSERT INTO "public"."tech" ("x_pct", "y_pct", "era", "name", "type", "excludes_id", "prereq_id") VALUES (47.41, 10.64, 2, 'Creed', 'SOCIETY', null, null);
INSERT INTO "public"."tech" ("x_pct", "y_pct", "era", "name", "type", "excludes_id", "prereq_id") VALUES (54.5, 23.42, 2, 'Seedbank', 'SOCIETY', null, null);
INSERT INTO "public"."tech" ("x_pct", "y_pct", "era", "name", "type", "excludes_id", "prereq_id") VALUES (66.32, 4.3, 2, 'Diplomat''s Manse', 'SOCIETY', null, null);
INSERT INTO "public"."tech" ("x_pct", "y_pct", "era", "name", "type", "excludes_id", "prereq_id") VALUES (63.97, 42.42, 2, 'Markets', 'ECONOMY', null, null);
INSERT INTO "public"."tech" ("x_pct", "y_pct", "era", "name", "type", "excludes_id", "prereq_id") VALUES (73.4, 29.75, 2, 'Collective Will', 'ECONOMY', null, null);
INSERT INTO "public"."tech" ("x_pct", "y_pct", "era", "name", "type", "excludes_id", "prereq_id") VALUES (73.4, 58.3, 2, 'Dustlytics', 'ECONOMY', null, null);
INSERT INTO "public"."tech" ("x_pct", "y_pct", "era", "name", "type", "excludes_id", "prereq_id") VALUES (40.28, 64.64, 2, 'Materials Science', 'DISCOVERY', null, null);
INSERT INTO "public"."tech" ("x_pct", "y_pct", "era", "name", "type", "excludes_id", "prereq_id") VALUES (47.41, 77.3, 2, 'Geology', 'DISCOVERY', null, null);
INSERT INTO "public"."tech" ("x_pct", "y_pct", "era", "name", "type", "excludes_id", "prereq_id") VALUES (54.5, 64.64, 2, 'Hydromatic Laboratory', 'DISCOVERY', null, 7);
INSERT INTO "public"."tech" ("x_pct", "y_pct", "era", "name", "type", "excludes_id", "prereq_id") VALUES (21.32, 26.42, 3, 'Conscription', 'DEFENSE', null, null);
INSERT INTO "public"."tech" ("x_pct", "y_pct", "era", "name", "type", "excludes_id", "prereq_id") VALUES (30.78, 42, 3, 'The Wisdom of Garin', 'DEFENSE', null, null);
INSERT INTO "public"."tech" ("x_pct", "y_pct", "era", "name", "type", "excludes_id", "prereq_id") VALUES (21.32, 64.53, 3, 'Composite Materials', 'DEFENSE', null, null);
INSERT INTO "public"."tech" ("x_pct", "y_pct", "era", "name", "type", "excludes_id", "prereq_id") VALUES (28.45, 4.3, 3, 'Statecraft', 'SOCIETY', null, null);
INSERT INTO "public"."tech" ("x_pct", "y_pct", "era", "name", "type", "excludes_id", "prereq_id") VALUES (40.28, 23.42, 3, 'Citizenship', 'SOCIETY', null, null);
INSERT INTO "public"."tech" ("x_pct", "y_pct", "era", "name", "type", "excludes_id", "prereq_id") VALUES (47.41, 10.64, 3, 'Urban Planning', 'SOCIETY', null, null);
INSERT INTO "public"."tech" ("x_pct", "y_pct", "era", "name", "type", "excludes_id", "prereq_id") VALUES (54.5, 23.42, 3, 'Hydrology', 'SOCIETY', null, null);
INSERT INTO "public"."tech" ("x_pct", "y_pct", "era", "name", "type", "excludes_id", "prereq_id") VALUES (66.32, 4.3, 3, 'Embassy', 'SOCIETY', null, null);
INSERT INTO "public"."tech" ("x_pct", "y_pct", "era", "name", "type", "excludes_id", "prereq_id") VALUES (63.92, 32.75, 3, 'Pyrometallurgy', 'ECONOMY', null, null);
INSERT INTO "public"."tech" ("x_pct", "y_pct", "era", "name", "type", "excludes_id", "prereq_id") VALUES (63.92, 54.97, 3, 'Commerce', 'ECONOMY', null, null);
INSERT INTO "public"."tech" ("x_pct", "y_pct", "era", "name", "type", "excludes_id", "prereq_id") VALUES (73.4, 26.42, 3, 'Arboreal Insights', 'ECONOMY', null, null);
INSERT INTO "public"."tech" ("x_pct", "y_pct", "era", "name", "type", "excludes_id", "prereq_id") VALUES (73.4, 64.53, 3, 'Dustnomics', 'ECONOMY', null, null);
INSERT INTO "public"."tech" ("x_pct", "y_pct", "era", "name", "type", "excludes_id", "prereq_id") VALUES (40.28, 70.86, 3, 'Research Grants', 'DISCOVERY', null, null);
INSERT INTO "public"."tech" ("x_pct", "y_pct", "era", "name", "type", "excludes_id", "prereq_id") VALUES (54.44, 70.86, 3, 'Collective Sacrifice', 'DISCOVERY', null, null);
INSERT INTO "public"."tech" ("x_pct", "y_pct", "era", "name", "type", "excludes_id", "prereq_id") VALUES (16.63, 26.64, 4, 'Auxiliary Forces', 'DEFENSE', 40, null);
INSERT INTO "public"."tech" ("x_pct", "y_pct", "era", "name", "type", "excludes_id", "prereq_id") VALUES (26.09, 26.64, 4, 'Logistics', 'DEFENSE', 39, null);
INSERT INTO "public"."tech" ("x_pct", "y_pct", "era", "name", "type", "excludes_id", "prereq_id") VALUES (30.78, 42, 4, 'The Gaze of Garin', 'DEFENSE', null, null);
INSERT INTO "public"."tech" ("x_pct", "y_pct", "era", "name", "type", "excludes_id", "prereq_id") VALUES (21.32, 61.42, 4, 'Zelevas'' Stamina', 'DEFENSE', null, null);
INSERT INTO "public"."tech" ("x_pct", "y_pct", "era", "name", "type", "excludes_id", "prereq_id") VALUES (28.45, 4.42, 4, 'Public Works', 'SOCIETY', 44, null);
INSERT INTO "public"."tech" ("x_pct", "y_pct", "era", "name", "type", "excludes_id", "prereq_id") VALUES (37.9, 4.42, 4, 'Dramatic Arts', 'SOCIETY', 43, null);
INSERT INTO "public"."tech" ("x_pct", "y_pct", "era", "name", "type", "excludes_id", "prereq_id") VALUES (47.41, 10.71, 4, 'Dignitary Goodwill', 'SOCIETY', null, null);
INSERT INTO "public"."tech" ("x_pct", "y_pct", "era", "name", "type", "excludes_id", "prereq_id") VALUES (56.87, 4.42, 4, 'Cultivation', 'SOCIETY', 47, null);
INSERT INTO "public"."tech" ("x_pct", "y_pct", "era", "name", "type", "excludes_id", "prereq_id") VALUES (66.31, 4.42, 4, 'Hothouses', 'SOCIETY', 46, null);
INSERT INTO "public"."tech" ("x_pct", "y_pct", "era", "name", "type", "excludes_id", "prereq_id") VALUES (68.71, 26.53, 4, 'Guilds', 'ECONOMY', 49, null);
INSERT INTO "public"."tech" ("x_pct", "y_pct", "era", "name", "type", "excludes_id", "prereq_id") VALUES (78.19, 26.53, 4, 'Standardization', 'ECONOMY', 48, null);
INSERT INTO "public"."tech" ("x_pct", "y_pct", "era", "name", "type", "excludes_id", "prereq_id") VALUES (73.45, 42.42, 4, 'Banks', 'ECONOMY', null, null);
INSERT INTO "public"."tech" ("x_pct", "y_pct", "era", "name", "type", "excludes_id", "prereq_id") VALUES (73.4, 61.3, 4, 'Highway Patrol', 'ECONOMY', null, null);
INSERT INTO "public"."tech" ("x_pct", "y_pct", "era", "name", "type", "excludes_id", "prereq_id") VALUES (40.26, 64.64, 4, 'Mercenaries', 'DISCOVERY', null, null);
INSERT INTO "public"."tech" ("x_pct", "y_pct", "era", "name", "type", "excludes_id", "prereq_id") VALUES (47.36, 77.16, 4, 'Digs', 'DISCOVERY', null, null);
INSERT INTO "public"."tech" ("x_pct", "y_pct", "era", "name", "type", "excludes_id", "prereq_id") VALUES (54.46, 64.64, 4, 'Aquadynamics', 'DISCOVERY', null, null);
INSERT INTO "public"."tech" ("x_pct", "y_pct", "era", "name", "type", "excludes_id", "prereq_id") VALUES (30.8, 32.97, 5, 'Military Engineering', 'DEFENSE', null, null);
INSERT INTO "public"."tech" ("x_pct", "y_pct", "era", "name", "type", "excludes_id", "prereq_id") VALUES (18.97, 20.19, 5, 'Armor Design', 'DEFENSE', null, 55);
INSERT INTO "public"."tech" ("x_pct", "y_pct", "era", "name", "type", "excludes_id", "prereq_id") VALUES (23.71, 42.3, 5, 'The Nurture of Garin', 'DEFENSE', null, null);
INSERT INTO "public"."tech" ("x_pct", "y_pct", "era", "name", "type", "excludes_id", "prereq_id") VALUES (23.71, 61.31, 5, 'Elite Focus', 'DEFENSE', null, null);
INSERT INTO "public"."tech" ("x_pct", "y_pct", "era", "name", "type", "excludes_id", "prereq_id") VALUES (37.88, 20.19, 5, 'Glory of Empire', 'SOCIETY', null, null);
INSERT INTO "public"."tech" ("x_pct", "y_pct", "era", "name", "type", "excludes_id", "prereq_id") VALUES (28.44, 4.26, 5, 'Imperial Bureaucracy', 'SOCIETY', null, 59);
INSERT INTO "public"."tech" ("x_pct", "y_pct", "era", "name", "type", "excludes_id", "prereq_id") VALUES (56.84, 20.19, 5, 'Preservation', 'SOCIETY', null, null);
INSERT INTO "public"."tech" ("x_pct", "y_pct", "era", "name", "type", "excludes_id", "prereq_id") VALUES (66.32, 4.34, 5, 'Cultural Education', 'SOCIETY', null, null);
INSERT INTO "public"."tech" ("x_pct", "y_pct", "era", "name", "type", "excludes_id", "prereq_id") VALUES (73.45, 23.3, 5, 'Large-scale Demolition', 'ECONOMY', null, null);
INSERT INTO "public"."tech" ("x_pct", "y_pct", "era", "name", "type", "excludes_id", "prereq_id") VALUES (73.45, 42.42, 5, 'Financial Literacy', 'ECONOMY', null, null);
INSERT INTO "public"."tech" ("x_pct", "y_pct", "era", "name", "type", "excludes_id", "prereq_id") VALUES (68.71, 61.42, 5, 'Tolls and Taxation', 'ECONOMY', 66, null);
INSERT INTO "public"."tech" ("x_pct", "y_pct", "era", "name", "type", "excludes_id", "prereq_id") VALUES (78.19, 61.42, 5, 'Land Management', 'ECONOMY', 65, null);
INSERT INTO "public"."tech" ("x_pct", "y_pct", "era", "name", "type", "excludes_id", "prereq_id") VALUES (30.8, 80.44, 5, 'University', 'DISCOVERY', 68, null);
INSERT INTO "public"."tech" ("x_pct", "y_pct", "era", "name", "type", "excludes_id", "prereq_id") VALUES (40.26, 80.42, 5, 'Inventors'' Endowments', 'DISCOVERY', 67, null);
INSERT INTO "public"."tech" ("x_pct", "y_pct", "era", "name", "type", "excludes_id", "prereq_id") VALUES (47.36, 70.97, 5, 'Anomanology', 'DISCOVERY', null, null);
INSERT INTO "public"."tech" ("x_pct", "y_pct", "era", "name", "type", "excludes_id", "prereq_id") VALUES (54.44, 64.64, 5, 'Scientific Prizes', 'DISCOVERY', null, null);
INSERT INTO "public"."tech" ("x_pct", "y_pct", "era", "name", "type", "excludes_id", "prereq_id") VALUES (61.56, 80.42, 5, 'Research Institute', 'DISCOVERY', null, 70);
INSERT INTO "public"."tech" ("x_pct", "y_pct", "era", "name", "type", "excludes_id", "prereq_id") VALUES (27.06, 45, 6, 'Military Conditioning', 'DEFENSE', null, null);
INSERT INTO "public"."tech" ("x_pct", "y_pct", "era", "name", "type", "excludes_id", "prereq_id") VALUES (41.63, 11.75, 6, 'Mass Psychology', 'SOCIETY', null, null);
INSERT INTO "public"."tech" ("x_pct", "y_pct", "era", "name", "type", "excludes_id", "prereq_id") VALUES (51.51, 11.63, 6, 'Civilization Optimizations', 'SOCIETY', null, null);
INSERT INTO "public"."tech" ("x_pct", "y_pct", "era", "name", "type", "excludes_id", "prereq_id") VALUES (66.63, 29.5, 6, 'Stock Exchange', 'ECONOMY', null, null);
INSERT INTO "public"."tech" ("x_pct", "y_pct", "era", "name", "type", "excludes_id", "prereq_id") VALUES (67.15, 56.23, 6, 'Dust Seismology', 'ECONOMY', null, null);
INSERT INTO "public"."tech" ("x_pct", "y_pct", "era", "name", "type", "excludes_id", "prereq_id") VALUES (47.4, 73.83, 6, 'Arcana of the Ancients', 'DISCOVERY', null, null);
INSERT INTO "public"."tech" ("x_pct", "y_pct", "era", "name", "type", "excludes_id", "prereq_id") VALUES (54.48, 23.34, 1, 'Corrosive Saliva', 'ECONOMY', null, null);
INSERT INTO "public"."tech" ("x_pct", "y_pct", "era", "name", "type", "excludes_id", "prereq_id") VALUES (21.3, 58, 2, 'Razor Mandibles', 'DEFENSE', null, null);
INSERT INTO "public"."tech" ("x_pct", "y_pct", "era", "name", "type", "excludes_id", "prereq_id") VALUES (73.4, 29.75, 2, 'Matriarch''s Orison', 'SOCIETY', null, null);
INSERT INTO "public"."tech" ("x_pct", "y_pct", "era", "name", "type", "excludes_id", "prereq_id") VALUES (56.78, 4.24, 2, 'Fungal Lab', 'SOCIETY', null, null);
INSERT INTO "public"."tech" ("x_pct", "y_pct", "era", "name", "type", "excludes_id", "prereq_id") VALUES (73.44, 45.57, 3, 'Matriarch''s Rise', 'DISCOVERY', null, null);
INSERT INTO "public"."tech" ("x_pct", "y_pct", "era", "name", "type", "excludes_id", "prereq_id") VALUES (21.32, 64.53, 3, 'Hive Guardian', 'DEFENSE', null, null);
INSERT INTO "public"."tech" ("x_pct", "y_pct", "era", "name", "type", "excludes_id", "prereq_id") VALUES (73.45, 42.42, 4, 'Matriarch''s Glory', 'ECONOMY', null, null);
INSERT INTO "public"."tech" ("x_pct", "y_pct", "era", "name", "type", "excludes_id", "prereq_id") VALUES (21.32, 61.42, 4, 'Chitinous Plating', 'DEFENSE', null, null);
INSERT INTO "public"."tech" ("x_pct", "y_pct", "era", "name", "type", "excludes_id", "prereq_id") VALUES (54.43, 23.23, 4, 'Accelerated Larvae', 'SOCIETY', null, null);
INSERT INTO "public"."tech" ("x_pct", "y_pct", "era", "name", "type", "excludes_id", "prereq_id") VALUES (63.91, 42.46, 1, 'Feudalism', 'ECONOMY', null, null);
INSERT INTO "public"."tech" ("x_pct", "y_pct", "era", "name", "type", "excludes_id", "prereq_id") VALUES (47.35, 67.68, 1, 'Saiadhan Inquisition', 'DISCOVERY', null, null);
INSERT INTO "public"."tech" ("x_pct", "y_pct", "era", "name", "type", "excludes_id", "prereq_id") VALUES (33.18, 77.22, 2, 'Thanatology', 'DISCOVERY', null, null);
INSERT INTO "public"."tech" ("x_pct", "y_pct", "era", "name", "type", "excludes_id", "prereq_id") VALUES (21.3, 58, 2, 'Lords'' Discipline', 'DEFENSE', null, null);
INSERT INTO "public"."tech" ("x_pct", "y_pct", "era", "name", "type", "excludes_id", "prereq_id") VALUES (21.32, 64.53, 3, 'Lords'' Piety', 'DEFENSE', null, null);
INSERT INTO "public"."tech" ("x_pct", "y_pct", "era", "name", "type", "excludes_id", "prereq_id") VALUES (63.96, 42.34, 4, 'Penitent Shrine', 'ECONOMY', null, null);
INSERT INTO "public"."tech" ("x_pct", "y_pct", "era", "name", "type", "excludes_id", "prereq_id") VALUES (21.32, 61.42, 4, 'Supreme Fealty', 'DEFENSE', null, null);
INSERT INTO "public"."tech" ("x_pct", "y_pct", "era", "name", "type", "excludes_id", "prereq_id") VALUES (23.71, 61.31, 5, 'Sacred Vow', 'DEFENSE', null, null);
INSERT INTO "public"."tech" ("x_pct", "y_pct", "era", "name", "type", "excludes_id", "prereq_id") VALUES (47.35, 67.68, 1, 'Celestial Scrying', 'DISCOVERY', null, null);
INSERT INTO "public"."tech" ("x_pct", "y_pct", "era", "name", "type", "excludes_id", "prereq_id") VALUES (61.62, 77.23, 2, 'Deciphering Stone', 'DISCOVERY', null, null);
INSERT INTO "public"."tech" ("x_pct", "y_pct", "era", "name", "type", "excludes_id", "prereq_id") VALUES (21.3, 58, 2, 'Sage''s Blessing', 'DEFENSE', null, null);
INSERT INTO "public"."tech" ("x_pct", "y_pct", "era", "name", "type", "excludes_id", "prereq_id") VALUES (33.18, 77.22, 2, 'Stargazing', 'DISCOVERY', null, null);
INSERT INTO "public"."tech" ("x_pct", "y_pct", "era", "name", "type", "excludes_id", "prereq_id") VALUES (21.32, 64.53, 3, 'Sages'' Wisdom', 'DEFENSE', null, null);
INSERT INTO "public"."tech" ("x_pct", "y_pct", "era", "name", "type", "excludes_id", "prereq_id") VALUES (21.32, 61.42, 4, 'Sages'' Insight', 'DEFENSE', null, null);
INSERT INTO "public"."tech" ("x_pct", "y_pct", "era", "name", "type", "excludes_id", "prereq_id") VALUES (33.18, 77.22, 4, 'Stellar Astronomy', 'DISCOVERY', null, null);
INSERT INTO "public"."tech" ("x_pct", "y_pct", "era", "name", "type", "excludes_id", "prereq_id") VALUES (23.71, 61.31, 5, 'Sages'' Vision', 'DEFENSE', null, null);
INSERT INTO "public"."tech" ("x_pct", "y_pct", "era", "name", "type", "excludes_id", "prereq_id") VALUES (40.26, 23.35, 1, 'Asceticism', 'DEFENSE', null, null);
INSERT INTO "public"."tech" ("x_pct", "y_pct", "era", "name", "type", "excludes_id", "prereq_id") VALUES (21.3, 58, 2, 'Choral Amplifier', 'DEFENSE', null, null);
INSERT INTO "public"."tech" ("x_pct", "y_pct", "era", "name", "type", "excludes_id", "prereq_id") VALUES (37.92, 4.35, 2, 'Persuasion', 'SOCIETY', null, null);
INSERT INTO "public"."tech" ("x_pct", "y_pct", "era", "name", "type", "excludes_id", "prereq_id") VALUES (21.32, 62.25, 3, 'Coral Sensorium', 'DEFENSE', null, null);
INSERT INTO "public"."tech" ("x_pct", "y_pct", "era", "name", "type", "excludes_id", "prereq_id") VALUES (37.92, 4.35, 3, 'Glorification', 'SOCIETY', null, null);
INSERT INTO "public"."tech" ("x_pct", "y_pct", "era", "name", "type", "excludes_id", "prereq_id") VALUES (40.32, 23.05, 4, 'Synaptic Acceleration', 'SOCIETY', null, null);
INSERT INTO "public"."tech" ("x_pct", "y_pct", "era", "name", "type", "excludes_id", "prereq_id") VALUES (21.32, 61.42, 4, 'Meditative Routines', 'DEFENSE', null, null);
INSERT INTO "public"."tech" ("x_pct", "y_pct", "era", "name", "type", "excludes_id", "prereq_id") VALUES (23.71, 59.14, 5, 'Harmonized Chorus', 'DEFENSE', null, null);

-- Reset sequences after insert data
SELECT setval('tech_id_seq', (SELECT COALESCE(MAX(id),0) FROM "tech"));
