SET CONSTRAINTS ALL DEFERRED;

INSERT INTO "public"."unit_skills" ("amount", "name", "target", "type") VALUES (0, 'Run Through I', '', '');
INSERT INTO "public"."unit_skills" ("amount", "name", "target", "type") VALUES (0, 'Opportunist I', '', '');
INSERT INTO "public"."unit_skills" ("amount", "name", "target", "type") VALUES (0, 'Impenetrable Momentum', '', '');
INSERT INTO "public"."unit_skills" ("amount", "name", "target", "type") VALUES (0, 'Breaching Attack II', '', '');
INSERT INTO "public"."unit_skills" ("amount", "name", "target", "type") VALUES (0, 'Righteous Wrath', '', '');
INSERT INTO "public"."unit_skills" ("amount", "name", "target", "type") VALUES (0, 'Cruel', '', '');
INSERT INTO "public"."unit_skills" ("amount", "name", "target", "type") VALUES (0, 'Life from Death', '', '');
INSERT INTO "public"."unit_skills" ("amount", "name", "target", "type") VALUES (0, 'Defense Expert I', '', '');
INSERT INTO "public"."unit_skills" ("amount", "name", "target", "type") VALUES (0, 'Run Through II', '', '');
INSERT INTO "public"."unit_skills" ("amount", "name", "target", "type") VALUES (0, 'Warmaster', '', '');
INSERT INTO "public"."unit_skills" ("amount", "name", "target", "type") VALUES (0, 'Defensive Aura', '', '');
INSERT INTO "public"."unit_skills" ("amount", "name", "target", "type") VALUES (0, 'Defensive Aura I', '', '');
INSERT INTO "public"."unit_skills" ("amount", "name", "target", "type") VALUES (0, 'Collateral Damage II', '', '');
INSERT INTO "public"."unit_skills" ("amount", "name", "target", "type") VALUES (0, 'Infectious', '', '');
INSERT INTO "public"."unit_skills" ("amount", "name", "target", "type") VALUES (0, 'Steady Blow I', '', '');
INSERT INTO "public"."unit_skills" ("amount", "name", "target", "type") VALUES (0, 'Wild Swing II', '', '');
INSERT INTO "public"."unit_skills" ("amount", "name", "target", "type") VALUES (0, 'Accurse I', '', '');
INSERT INTO "public"."unit_skills" ("amount", "name", "target", "type") VALUES (0, 'Coordinated Attack I', '', '');
INSERT INTO "public"."unit_skills" ("amount", "name", "target", "type") VALUES (0, 'Defensive Aura II', '', '');
INSERT INTO "public"."unit_skills" ("amount", "name", "target", "type") VALUES (0, 'Destabilizing Defense I', '', '');
INSERT INTO "public"."unit_skills" ("amount", "name", "target", "type") VALUES (0, 'Defense Expert II', '', '');
INSERT INTO "public"."unit_skills" ("amount", "name", "target", "type") VALUES (0, 'Breaching Attack I', '', '');
INSERT INTO "public"."unit_skills" ("amount", "name", "target", "type") VALUES (0, 'Weakening Strike II', '', '');
INSERT INTO "public"."unit_skills" ("amount", "name", "target", "type") VALUES (0, 'Leeching Strike II', '', '');
INSERT INTO "public"."unit_skills" ("amount", "name", "target", "type") VALUES (0, 'Fearless Charge I', '', '');
INSERT INTO "public"."unit_skills" ("amount", "name", "target", "type") VALUES (0, 'Fearless Charge II', '', '');
INSERT INTO "public"."unit_skills" ("amount", "name", "target", "type") VALUES (0, 'Inspiring Strike II', '', '');
INSERT INTO "public"."unit_skills" ("amount", "name", "target", "type") VALUES (0, 'Blood Rush', '', '');
INSERT INTO "public"."unit_skills" ("amount", "name", "target", "type") VALUES (0, 'Ranged IV', '', '');
INSERT INTO "public"."unit_skills" ("amount", "name", "target", "type") VALUES (0, 'Terror', '', '');
INSERT INTO "public"."unit_skills" ("amount", "name", "target", "type") VALUES (0, 'Shattering Strike', '', '');
INSERT INTO "public"."unit_skills" ("amount", "name", "target", "type") VALUES (0, 'Ranged III', '', '');
INSERT INTO "public"."unit_skills" ("amount", "name", "target", "type") VALUES (0, 'Ranged V', '', '');
INSERT INTO "public"."unit_skills" ("amount", "name", "target", "type") VALUES (0, 'Flying', '', '');
INSERT INTO "public"."unit_skills" ("amount", "name", "target", "type") VALUES (0, 'Incapacitating Strike I', '', '');
INSERT INTO "public"."unit_skills" ("amount", "name", "target", "type") VALUES (0, 'Defiant Gaze', '', '');
INSERT INTO "public"."unit_skills" ("amount", "name", "target", "type") VALUES (0, 'Opportunist II', '', '');
INSERT INTO "public"."unit_skills" ("amount", "name", "target", "type") VALUES (0, 'Destabilizing Defense II', '', '');
INSERT INTO "public"."unit_skills" ("amount", "name", "target", "type") VALUES (0, 'Blood Mending II', '', '');
INSERT INTO "public"."unit_skills" ("amount", "name", "target", "type") VALUES (0, 'Patroller I', '', '');
INSERT INTO "public"."unit_skills" ("amount", "name", "target", "type") VALUES (0, 'Targeting', '', '');
INSERT INTO "public"."unit_skills" ("amount", "name", "target", "type") VALUES (0, 'Accurse II', '', '');
INSERT INTO "public"."unit_skills" ("amount", "name", "target", "type") VALUES (0, 'Weakening Strike I', '', '');
INSERT INTO "public"."unit_skills" ("amount", "name", "target", "type") VALUES (0, 'Collateral Damage', '', '');
INSERT INTO "public"."unit_skills" ("amount", "name", "target", "type") VALUES (0, 'Shield Mastery II', '', '');
INSERT INTO "public"."unit_skills" ("amount", "name", "target", "type") VALUES (0, 'Patroller II', '', '');
INSERT INTO "public"."unit_skills" ("amount", "name", "target", "type") VALUES (0, 'Shield Mastery I', '', '');
INSERT INTO "public"."unit_skills" ("amount", "name", "target", "type") VALUES (0, 'Heads-Up! I', '', '');
INSERT INTO "public"."unit_skills" ("amount", "name", "target", "type") VALUES (0, 'Defensive Plate', '', '');
INSERT INTO "public"."unit_skills" ("amount", "name", "target", "type") VALUES (0, 'Leeching Strike I', '', '');
INSERT INTO "public"."unit_skills" ("amount", "name", "target", "type") VALUES (0, 'Never Yielding', '', '');
INSERT INTO "public"."unit_skills" ("amount", "name", "target", "type") VALUES (0, 'Collateral Damage I', '', '');
INSERT INTO "public"."unit_skills" ("amount", "name", "target", "type") VALUES (0, 'Blood Mending I', '', '');
INSERT INTO "public"."unit_skills" ("amount", "name", "target", "type") VALUES (0, 'Terror I', '', '');
INSERT INTO "public"."unit_skills" ("amount", "name", "target", "type") VALUES (0, 'Chosen''s Wrath', '', '');
INSERT INTO "public"."unit_skills" ("amount", "name", "target", "type") VALUES (0, 'Breaching Attack', '', '');
INSERT INTO "public"."unit_skills" ("amount", "name", "target", "type") VALUES (0, 'Seismic Slash', '', '');
INSERT INTO "public"."unit_skills" ("amount", "name", "target", "type") VALUES (0, 'Coordinated Attack II', '', '');
INSERT INTO "public"."unit_skills" ("amount", "name", "target", "type") VALUES (0, 'Steady Blow II', '', '');
INSERT INTO "public"."unit_skills" ("amount", "name", "target", "type") VALUES (0, 'Heads-Up! II', '', '');
INSERT INTO "public"."unit_skills" ("amount", "name", "target", "type") VALUES (0, 'Leeching Strike', '', '');
INSERT INTO "public"."unit_skills" ("amount", "name", "target", "type") VALUES (0, 'Aware', '', '');
INSERT INTO "public"."unit_skills" ("amount", "name", "target", "type") VALUES (0, 'Protective Oversight', '', '');
INSERT INTO "public"."unit_skills" ("amount", "name", "target", "type") VALUES (0, 'Inspiring Strike I', '', '');
INSERT INTO "public"."unit_skills" ("amount", "name", "target", "type") VALUES (0, 'Obliteration', '', '');
INSERT INTO "public"."unit_skills" ("amount", "name", "target", "type") VALUES (0, 'Incapacitating Strike II', '', '');
INSERT INTO "public"."unit_skills" ("amount", "name", "target", "type") VALUES (0, 'Feast on the Dead', '', '');

-- Reset sequences after insert data
SELECT setval('unit_skills_id_seq', (SELECT COALESCE(MAX(id),0) FROM "unit_skills"));