package ewshop.app.migration;

import org.flywaydb.core.Flyway;
import org.junit.jupiter.api.Test;

import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.List;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

class TechPrerequisiteKeyMigrationTest {

    @Test
    void commonMigrations_shouldHardenTechPrerequisiteKeyTables() throws Exception {
        String url = "jdbc:h2:mem:flyway_tech_prereq_keys_" + UUID.randomUUID()
                + ";MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1";

        createPreExistingTechPrerequisiteTables(url);

        Flyway.configure()
                .dataSource(url, "sa", "")
                .locations("classpath:db/migration/common")
                .baselineOnMigrate(true)
                .baselineVersion("3.5.5")
                .target("3.5.6")
                .load()
                .migrate();

        try (var connection = DriverManager.getConnection(url, "sa", "")) {
            assertThat(tableExists(connection, "tech_prereq_key")).isTrue();
            assertThat(tableExists(connection, "tech_exclusive_prereq_key")).isTrue();

            assertThat(indexNames(connection, "tech_prereq_key"))
                    .contains("ix_tech_prereq_key_tech_id", "ix_tech_prereq_key_prereq_tech_key");
            assertThat(indexNames(connection, "tech_exclusive_prereq_key"))
                    .contains(
                            "ix_tech_exclusive_prereq_key_tech_id",
                            "ix_tech_exclusive_prereq_key_exclusive_prereq_tech_key"
                    );

            insertTechWithPrerequisiteKeys(connection);

            assertThatThrownBy(() -> insertPrereqKey(connection, 1, "Tech_Masonry"))
                    .isInstanceOf(SQLException.class);
            assertThatThrownBy(() -> insertExclusivePrereqKey(connection, 1, "Tech_Alternative"))
                    .isInstanceOf(SQLException.class);

            try (var statement = connection.createStatement()) {
                statement.executeUpdate("delete from tech where id = 1");
            }

            assertThat(rowCount(connection, "tech_prereq_key")).isZero();
            assertThat(rowCount(connection, "tech_exclusive_prereq_key")).isZero();
        }
    }

    private static void createPreExistingTechPrerequisiteTables(String url) throws SQLException {
        try (var connection = DriverManager.getConnection(url, "sa", "");
             var statement = connection.createStatement()) {
            statement.execute("""
                    create table tech (
                        id bigint generated by default as identity primary key,
                        name varchar(255) not null
                    )
                    """);
            statement.execute("""
                    create table tech_prereq_key (
                        id bigint generated by default as identity primary key,
                        tech_id bigint not null,
                        prereq_tech_key varchar(255) not null,
                        constraint fk_tech_prereq_key_tech foreign key (tech_id) references tech (id)
                    )
                    """);
            statement.execute("""
                    create unique index ux_tech_prereq_key
                        on tech_prereq_key (tech_id, prereq_tech_key)
                    """);
            statement.execute("""
                    create table tech_exclusive_prereq_key (
                        id bigint generated by default as identity primary key,
                        tech_id bigint not null,
                        exclusive_prereq_tech_key varchar(255) not null,
                        constraint fk_tech_exclusive_prereq_key_tech foreign key (tech_id) references tech (id)
                    )
                    """);
            statement.execute("""
                    create unique index ux_tech_exclusive_prereq_key
                        on tech_exclusive_prereq_key (tech_id, exclusive_prereq_tech_key)
                    """);
        }
    }

    private static void insertTechWithPrerequisiteKeys(java.sql.Connection connection) throws SQLException {
        try (var statement = connection.createStatement()) {
            statement.executeUpdate("insert into tech (id, name) values (1, 'Architecture')");
        }
        insertPrereqKey(connection, 1, "Tech_Masonry");
        insertExclusivePrereqKey(connection, 1, "Tech_Alternative");
    }

    private static void insertPrereqKey(
            java.sql.Connection connection,
            long techId,
            String prereqTechKey
    ) throws SQLException {
        try (var statement = connection.prepareStatement("""
                insert into tech_prereq_key (tech_id, prereq_tech_key)
                values (?, ?)
                """)) {
            statement.setLong(1, techId);
            statement.setString(2, prereqTechKey);
            statement.executeUpdate();
        }
    }

    private static void insertExclusivePrereqKey(
            java.sql.Connection connection,
            long techId,
            String exclusivePrereqTechKey
    ) throws SQLException {
        try (var statement = connection.prepareStatement("""
                insert into tech_exclusive_prereq_key (tech_id, exclusive_prereq_tech_key)
                values (?, ?)
                """)) {
            statement.setLong(1, techId);
            statement.setString(2, exclusivePrereqTechKey);
            statement.executeUpdate();
        }
    }

    private static boolean tableExists(java.sql.Connection connection, String tableName) throws SQLException {
        try (var statement = connection.prepareStatement("""
                select count(*)
                  from information_schema.tables
                 where table_schema = 'public'
                   and table_name = ?
                """)) {
            statement.setString(1, tableName);
            try (var resultSet = statement.executeQuery()) {
                resultSet.next();
                return resultSet.getInt(1) == 1;
            }
        }
    }

    private static List<String> indexNames(java.sql.Connection connection, String tableName) throws SQLException {
        try (var statement = connection.prepareStatement("""
                select lower(index_name)
                  from information_schema.indexes
                 where table_schema = 'public'
                   and table_name = ?
                """)) {
            statement.setString(1, tableName);
            try (var resultSet = statement.executeQuery()) {
                var names = new java.util.ArrayList<String>();
                while (resultSet.next()) {
                    names.add(resultSet.getString(1));
                }
                return names;
            }
        }
    }

    private static int rowCount(java.sql.Connection connection, String tableName) throws SQLException {
        try (var statement = connection.createStatement();
             var resultSet = statement.executeQuery("select count(*) from " + tableName)) {
            resultSet.next();
            return resultSet.getInt(1);
        }
    }
}
